doc/index.html

Fixes #22, and https://svn.boost.org/trac10/ticket/13033
This is pretty trivial, so I'll accept it myself and cherry pick to master if I don't get a response.

Fix link to video tutorial

---

test/Jamfile
test/fabscript

AFAIS, this define is not used anywhere across GIL.

Remove unused define BOOST_GIL_NO_IO

---

test/channel.cpp
test/image.cpp
test/pixel.cpp
test/pixel_iterator.cpp

Catch std::exception in main of test programs

---

io/test/png_read_test.cpp

Uncomment read_pixel_per_meter test case

---

README.md

Start README as a pretty entry point to the world of GIL :)
```
[![Gitter](https://badges.gitter.im/boostorg/gil.svg)](https://gitter.im/boostorg/gil?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge)
```

First stab at README

---

include/boost/gil/extension/toolbox/image_types/indexed_image.hpp
toolbox/test/indexed_image_test.cpp

Added new function to generate an indexed_image_view from two views. One for indices and palette.
- Boost version 1.67
- Compiler version: Visual Studio 2017

generate indexed_image_view

---

doc/design_guide.rst
doc/toolbox.rst
doc/tutorial.rst

Run spell-check corrections in `.rst` files.
Work submitted against @stefanseefeld `doc` branch.
(_Testing PR against a topic branch_ as more careful way for easier work synch, to avoid `git push --force` troubles, etc.)

[doc] Spell check

---

include/boost/gil/algorithm.hpp

Minor severity: compiler warning clean up
- Compiler version: MSVC 19.13.26129

Fix potentially uninitialized local variable y

---

.gitattributes

This also removes the git+svn cruft.

Refine .gitattributes to reflect current content of repository

---

include/boost/gil/packed_pixel.hpp
include/boost/gil/pixel.hpp
numeric/test/numeric.cpp
test/channel.cpp
test/pixel.cpp
test/pixel_iterator.cpp

Fix MSVC warning: C4100 unreferenced formal parameter

---

include/boost/gil/extension/io/bmp/detail/read.hpp

Adds comment that should make life of non-Windows users of BMP format easier.
- "Programming Windows", 5th Ed. by Charles Petzold  :-)

[io/bmp] Explain DIB orientation variants that affect reading

---

.circleci/config.yml

Add GCC 8.1 to CircleCI workflow based on the recently added official Docker images https://hub.docker.com/r/library/gcc/tags/

[circleci] Add GCC 8.1 jobs to workflow

---

include/boost/gil/extension/dynamic_image/algorithm.hpp
include/boost/gil/extension/dynamic_image/any_image_view.hpp
include/boost/gil/extension/dynamic_image/image_view_factory.hpp
include/boost/gil/extension/toolbox/image_types/indexed_image.hpp
include/boost/gil/io/device.hpp

This PR fixes warnings reported in https://lists.boost.org/boost-gil/2018/07/0071.php.

Fix (some) warnings.

---

test/CMakeLists.txt
test/Jamfile
test/point/CMakeLists.txt
test/point/Jamfile
test/point/point.cpp
test/point/point_concepts.cpp

Add basic tests for point<T>

---

include/boost/gil/io/read_image.hpp

Remove dependency on boost/algorithm/string.hpp as unused

---

include/boost/gil/point.hpp
include/boost/gil/utilities.hpp

Remove dependency on boost/config/no_tr1/cmath.hpp

---

include/boost/gil/extension/toolbox/image_types/subchroma_image.hpp

Rename `Scaling_Factors` to lower-case, as well as its template parameters.
Move `scaling_factors` to namespace `detail` and before it is use.
Fix access to `scaling_factors` members in derived classes.
Add missing `typename`.
Remove superfluous thus incorrect `typename`.
Remove `subchroma_image_view` implicit friends with self
- Fixes template parameter aliasing for Locator and Factors.
Subset of fixes from pending PR #164
- #164

Fix compilation of subchroma_image.hpp as self-contained headers

---

include/boost/gil/algorithm.hpp
io/test/color_space_write_test.hpp

Fix GCC -Wunused-parameter warnings

---

test/CMakeLists.txt
test/Jamfile
test/iterator/CMakeLists.txt
test/iterator/Jamfile
test/iterator/concepts.cpp

This is a basic test. Next, the plan is to add to the test checks for `iterator_from_2d`, `planar_pixel_iterator`, `position_iterator`, `step_iterator`, etc.
-----

Add test for iterator concepts

---

CMakeLists.txt

[cmake] Disable Boost autolinking for MSVC [skip travis]

---

.appveyor.yml
.travis.yml
test/pixel/CMakeLists.txt
test/pixel/Jamfile
test/pixel/pixels_are_compatible.cpp

Add test for pixels_are_compatible metafunction

---

doc/doxyfile

Make peace with @vinniefalco & @pdimov, not war!
-----
/cc @stefanseefeld Please, have a look at the `INPUT` list, is this correct?
- I don't know if it is Okey to remove `extension/io`
- What about `concepts/detail`, do we need it?
We need to fix it.

Update INPUT list in doc/doxyfile

---

.azure-pipelines.yml
.ci/azure-pipelines/steps-install-boost.yml
.ci/azure-pipelines/steps-install-conan.yml
CMakeLists.txt

- Compiler version: `msvc-14.0`
- #261
- #262
- https://github.com/Microsoft/azure-pipelines-image-generation/issues/374

Add build using VS2015 to Azure Pipelines

---

Jamfile

Some background about rationale behind this change can be found at
* https://github.com/boostorg/mp11/issues/31
* https://github.com/boostorg/build/issues/394

Disable pedantic compilation for CI builds

---

test/channel/CMakeLists.txt
test/channel/Jamfile
test/channel/is_integral.cpp
test/channel/packed_channel_value.cpp

Add test for packed_channel_value and is_integral specialization

---

test/extension/numeric/CMakeLists.txt
test/extension/numeric/kernel.cpp

Add FIXME and TODO comments about issues that needs to be clarified.
-----
/cc @miralshah365

Add tests for kernel_1d and kernel_1d_fixed classes

---

test/extension/numeric/Jamfile

Add kernel test to numeric/Jamfile

---

.travis.yml
doc/requirements.txt

Bump Sphinx version from 1.7.9 to 2.1

---

test/extension/numeric/convolve_2d.cpp

Minimal test for new function added in #347 (with identity kernel only).

Add test for convolve function from Numeric extension

---

include/boost/gil/image_processing/threshold.hpp

Prefer C++ style comments for Doxygen.

Update docs for threshold_binary function and enums

---

include/boost/gil/extension/numeric/channel_numeric_operations.hpp
test/core/channel/test_fixture.hpp
test/extension/numeric/CMakeLists.txt
test/extension/numeric/Jamfile
test/extension/numeric/channel_numeric_operations.cpp

Add static assertions to verify channel types are convertible to expected result type.
Add new and update existing Doxygen comments describing interfaces in `extension/numeric/channel_numeric_operations.hpp`.

Add tests for extension/numeric/channel_numeric_operations.hpp

---

test/extension/numeric/CMakeLists.txt
test/extension/numeric/Jamfile
test/extension/numeric/convolve.cpp

Accommodate to @miralshah365 's plan in #356 to add `convolve` function.

Rename test/extension/numeric/convolve_2d.cpp to convolve.cpp

---

doc/io.rst

Clarify what flavours of PNM formats can be read and written

---

include/boost/gil/extension/numeric/algorithm.hpp
include/boost/gil/extension/numeric/convolve.hpp

This is just a pedantic me trying to get the naming fully and right, hopefully.
> convolution is cross-correlation with kernel transposed by 180 degrees, around each axis.
- https://lists.boost.org/boost-gil/2019/07/0268.php
- https://en.wikipedia.org/wiki/Cross-correlation
- https://www.youtube.com/watch?v=C3EEy8adxvc

Clarify correlation as cross-correlation and convolution as spatial convolution

---

.appveyor.yml

For some reason, vcpkg stopped working on AppVeyor, https://ci.appveyor.com/project/stefanseefeld/gil/builds/26484475/job/srp33cpe4ld972ul
```
[00:00:00] Build started
[00:00:01] Fetching repository commit (7766a0f)...OK
[00:00:01] Total: 9.3 MB in 543 files
[00:00:05] Restoring build cache
[00:00:05] 
[00:00:05] Cache 'c:\tools\vcpkg\installed' - Downloading (5,445,875 bytes)...1%
[00:00:05] Cache 'c:\tools\vcpkg\installed' - Downloading (5,445,875 bytes)...10%
[00:00:05] Cache 'c:\tools\vcpkg\installed' - Downloading (5,445,875 bytes)...20%
[00:00:05] Cache 'c:\tools\vcpkg\installed' - Downloading (5,445,875 bytes)...30%
[00:00:05] Cache 'c:\tools\vcpkg\installed' - Downloading (5,445,875 bytes)...40%
[00:00:05] Cache 'c:\tools\vcpkg\installed' - Downloading (5,445,875 bytes)...50% …
```

[appveyor] Switch all jobs to VS2017 image

---

include/boost/gil/extension/numeric/pixel_numeric_operations.hpp
test/extension/numeric/CMakeLists.txt
test/extension/numeric/Jamfile
test/extension/numeric/pixel_numeric_operations.cpp

Add new and update existing Doxygen comments describing interfaces in `extension/numeric/pixel_numeric_operations.hpp`.

Add tests for extension/numeric/pixel_numeric_operations.hpp

---

include/boost/gil/image_processing/scaling.hpp
test/core/image_processing/lanczos_scaling.cpp
test/core/image_processing/simple_kernels.cpp

Add copyright and license to
simple_kernels.cpp and
lanczos_scaling.cpp files.
Closes https://github.com/boostorg/gil/issues/374
Parenthesize min and max
to avoid Windows's macros.
Closes https://github.com/boostorg/gil/issues/375

Fix inspection issues

---

include/boost/gil/io/device.hpp

The change removes asserts from low-level file I/O routines and replaces them by exceptions. This allows better handling of runtime conditions such as zero-length file or disk full.
https://github.com/boostorg/gil/issues/360

Replaced asserts by exceptions in low-level file I/O code

---

include/boost/gil/extension/numeric/convolve.hpp
include/boost/gil/extension/numeric/kernel.hpp
include/boost/gil/image_processing/threshold.hpp
test/extension/numeric/kernel.cpp

Guidelines violations resolved.
New copyright holder name added in required files
closes #376

Fix Boost guidelines violations

---

example/convolve2d.cpp
include/boost/gil/extension/numeric/algorithm.hpp
include/boost/gil/extension/numeric/convolve.hpp
include/boost/gil/image_processing/filter.hpp

`boundary_option` moved to `numeric/algorithm.hpp`
closes #387

`convolve_boundary_option` renamed to `boundary_option`

---

include/boost/gil/io/device.hpp

Fix void istream_device::read function returning a value

---

include/boost/gil/extension/io/png/old.hpp

The `gil/extension/io/{format}/old.hpp` interfaces are covered by old
tests which are part of full I/O test suite only. Due to limited CI
resources we do not run full tests, hence this has not been caught.
Fixes #408

Fix illegal narrowing conversion in png_read_dimensions

---

example/sobel_scharr.cpp

corrected namespace for 2dconvolution in `sobel_scharr.cpp`
- ~[ ] Ensure all CI builds pass~ No need to wait

Corrected the namespace in example

---

test/extension/io/png_read_test.cpp

corrected header for the unit test in `png_read_test.cpp`

Test correction

---

example/Jamfile

Edit the Jamfile in /example to ensure all examples build without errors.
https://github.com/boostorg/gil/issues/436

Completed the Jamfile configuration to make sure all example codes compile

---

include/boost/gil/concepts/channel.hpp
include/boost/gil/concepts/image_view.hpp
include/boost/gil/image_processing/threshold.hpp

Fixed some typos

---

.travis.yml

Travis CI: Add GCC 9 and set GCC jobs to build cxxstd=11,14,17,2a

---

.appveyor.yml
.ci/azure-pipelines/steps-install-boost.yml
.ci/get-boost.sh
CMakeLists.txt
CONTRIBUTING.md

Clean up CI and CMake from Boost.Test and Boost.System remains

---

include/boost/gil/algorithm.hpp
include/boost/gil/image.hpp
test/legacy/image.cpp

Killing some more annoying lengthy warning outputs

Fix -Wsign-compare warning in uses of num_channels metafunction

---

doc/tutorial/gradient.rst

Updates doc at https://boostorg.github.io/gil/html/tutorial/gradient.html

Fix typo and replace mpl with mp11 in tutorial

---

conanfile.txt

Discussion at https://github.com/conan-io/conan-center-index/issues/4151#issuecomment-757902106
Fixes Azure Pipelines builds for #535

build: Switch conan packages from bincrafters to conan.io

---

conanfile.txt

Discussion at https://github.com/conan-io/conan-center-index/issues/4151#issuecomment-757902106
(cherry picked from develop commit 0c0fe1ae79053d8aedfa95eca39329d135e4ea1c)
- Cherry-picked from #537

build: Switch conan packages from bincrafters to conan.io in master

---

include/boost/gil/image_processing/hessian.hpp

added missing copyright info
<boost/gil/image_processing/hessian.hpp>

added missing copyright info

---

doc/design/color_space.rst
doc/design/concepts.rst
doc/design/point.rst

Correct typos in documentation

[fix] Correct typos in documentation

---

doc/design/color_base.rst
doc/design/color_space.rst
doc/design/metafunctions.rst
doc/design/pixel_iterator.rst
doc/io.rst

Remove remaining references to MPL in the documentation

---

RELEASES.md

Adds release notes for the changes that were merged in #654.
See #654 and the related issue #519.

docs: add release notes for issue #654

---

include/boost/gil/io/typedefs.hpp

This is intended to address #763
Required:

Propose repair for issue 763

---

doc/design/channel.rst
doc/design/examples.rst
doc/design/extending.rst
doc/design/image.rst
doc/design/image_view.rst
doc/design/metafunctions.rst
doc/design/pixel_locator.rst
doc/histogram/extend.rst
doc/histogram/overview.rst
doc/image_processing/affine-region-detectors.rst
doc/image_processing/basics.rst
doc/image_processing/contrast_enhancement/overview.rst
doc/installation.rst
doc/io.rst
doc/naming.rst
doc/tutorial/gradient.rst
doc/tutorial/histogram.rst

I have corrected some minor mistakes.

Fix mistakes
