boostorg/gil

include/boost/gil/extension/io/formats/targa/reader_backend.hpp

Likely, committed by accident as part of fix of #33 
-----
This cruft was added in https://github.com/boostorg/gil/commit/fe8dcea00d4ae393ddbe0c92909026e39731375b
@chhenning  I have no idea how this slipped through CI builds :)

Remove uncommented raw URL

---

include/boost/gil/extension/io/formats/jpeg/writer_backend.hpp

Apparently, clang-802.0.42 (Apple LLVM version 8.1.0) is complaining as per the recent Travis CI build failures.

Fix implicit int to libjpeg boolean conversion

---

.appveyor.yml

Fix GIL IO tests issue with dependency DLLs not found.
-----
/cc @chhenning, @stefanseefeld 
```
D:\dev\boost\boost\libs\gil (ml/add-vcpkg-bin-to-path) b2 address-model=32 include=%I% library-path=%L% io/test//simple
..\..\libs\log\build\Jamfile.v2:45: Unescaped special character in argument <define>$(flag)=1
D:/dev/boost/boost/libs/predef/check/../tools/check\predef.jam:46: Unescaped special character in argument $(language)::$(expression)
Performing configuration checks
- default address-model    : 32-bit (cached)
- default architecture     : x86 (cached)
- symlinks supported       : yes (cached)
- BOOST_COMP_GNUC >= 4.3.0 : no  (cached)
- libjpeg                  : yes (cached)
- zlib                     : yes (cached)
- libpng                   : yes (cached)
- libtiff …
```

Add vcpkg bin folder to PATH

---

include/boost/gil/extension/io/formats/targa/reader_backend.hpp

Ensure that for TARGA Data Type 1, entire descriptor byte is set to 0.
-----
/cc @chhenning, @stefanseefeld 
According to the TGA Specification, http://www.paulbourke.net/dataformats/tga/, regardless of the Data Type (apart from Data Type 1):
> For the Targa 24, it should be 0.
For Targa 24bpp images, the original of `if(_info._bits_per_pixel == 24 && _info._descriptor != 0 )` is false and skips directly to the following `else` clause which throws `io_error("Unsupported descriptor for targa file")`.
This caused failures of `non_bit_aligned_image_test` in `all_formats_test.cpp`.
Might be related to #33
This also cleans up garbage URL removed in #41

Fix test of TARGA header descriptor for 24bpp file

---

test/image.cpp

Print calculate checksum in test output and print expected checksum too in case of test case failure.
Helpful also for investigation of test failure reported in #46

Allow test/image.cpp accept checksums file via command line argument

---

.appveyor.yml
.editorconfig
CMakeLists.txt
CMakeSettings.json
conanfile.txt
example/CMakeLists.txt
io/test/CMakeLists.txt
numeric/test/CMakeLists.txt
test/CMakeLists.txt
toolbox/test/CMakeLists.txt

Add basic CMake configuration for Boost.GIL
First stab at collection of `CMakeLists.txt` for Boost.GIL
- Allow building and testing boostorg/gil against Boost from cloned superproject or installed distribution.
Add `CMakeSettings.json` config file for VS2017 integration with CMake
- Defines build configurations for VS and Ninja generators.
- Can be used as is or as a template ready to customise.
Add `conanfile.txt `for Conan package manager (eg. for `cmake -DGIL_USE_CONAN=ON`).
Add `.editignore` file to with basic encoding of CMake and CI scripts.
Update `.appveyor.yml` with two extra CMake-based builds (allowed to fail).
-----
Provide CMake build configuration for convenient development, building and debugging using CMake-based IDEs.
Allow building and testing Boost.GIL against staged …

Add basic CMake configuration for Boost.GIL

---

include/boost/gil/channel_algorithm.hpp
include/boost/gil/extension/io/formats/bmp/reader_backend.hpp
include/boost/gil/extension/io/formats/bmp/scanline_read.hpp
include/boost/gil/extension/io/formats/bmp/write.hpp
include/boost/gil/extension/io/formats/png/writer_backend.hpp

More fixes of potential UB due to overflowing bit-shift operation
Patch courtesy of @Lastique via Boost ML.
Continuation of SHA-1: 90c2deb725db4dda408b065e130f19553574953d
#46, #50, #51 and hopefully it also fixes the checksum bug #49

Fixes of potential UB due to overflowing bit-shift operation

---

include/boost/gil/extension/io/formats/bmp/scanline_read.hpp
include/boost/gil/extension/io/formats/bmp/write.hpp
include/boost/gil/extension/io/formats/png/read.hpp
include/boost/gil/extension/io/formats/pnm/write.hpp
include/boost/gil/extension/io/formats/targa/reader_backend.hpp
include/boost/gil/extension/io/formats/tiff/read.hpp
include/boost/gil/extension/toolbox/color_spaces/hsl.hpp
include/boost/gil/gil_concept.hpp

This change suppresses lots of warnings on GCC all stemming from the use of (pseudo-)concepts to validate the use of template parameters in GIL code.

Suppress concept-related compiler warnings.

---

.appveyor.yml
include/boost/gil/channel_algorithm.hpp
test/image.cpp

/cc @chhenning, @stefanseefeld yet another curious case :)
For `variant-debug` all tests pass - this is the default AppVeyor builds variant for current the master.
For `variant=release`, run for `test/image.cpp` will likely fail due to mismatch of CRC calculated `bgr121_basic_red_x` image.

Add AppVeyor jobs for b2 variant=release

---

include/boost/gil/channel.hpp

Pre-defined packed_channel_reference_base::set::num_values already
represents the value.
Fixes warning C4458: declaration of 'num_values' hides class member
- Compiler version: VS2017

Remove redundant local num_values in packed_channel_reference_base::set()

---

Jamfile.v2
io/test/Jamfile
numeric/test/Jamfile
test/Jamfile
toolbox/test/Jamfile

- Group compilation flags and defines in common top-level Jamfile - relies on Boost.Build feature of referring parent Jamfile-s.
- Bump MSVC warning level to W4
- Preparing for detailed warnings clean up based on:
https://svn.boost.org/trac10/wiki/Guidelines/WarningsGuidelines
I'm hopeful it will also help to investigate #49

Extend GCC and clang cxxflags for detailed warnings

---

.travis.yml

This aims to confirm there are no issues depending on build configuration (related to #46 and #49).
#51 
-----
BTW, `variant=debug,release` is intentional, it first builds tests with `variant=debug`, then `variant=release`.

Add variant=release to Travis CI builds of tests

---

include/boost/gil/image.hpp

Replace them by their cousins from std::allocator_traits.
Signed-off-by: Daniela Engert <dani@ngrt.de>

Most members of std::allocate are deprecated in C++17

---

sublibs

The feature is documented only in [regression code](https://github.com/boostorg/regression/blob/35d42b5d50dff7008374807aa136ddf26a97a2fd/common/src/process_jam_log.cpp#L228-L238), but widely used in boost.

Added sublibs file telling regression tools that subdirs contain library tests

---

include/boost/gil/algorithm.hpp
include/boost/gil/channel_algorithm.hpp
include/boost/gil/gil_concept.hpp
include/boost/gil/virtual_locator.hpp

Cleans up a bunch of warnings reported for minimalistic
```
#include <boost/gil.hpp>
int main() {}
```
namely:
- unused parameter
- shadowed typedef
- implicit conversion changes signedness:
int to signed <int>
int to unsigned <int>
Note, arithmetic op is performed on `int` as higher rank type with result is in range of return type, safe to cast.
- Compiler version: clang 6

Fix some warnings reported by clang

---

include/boost/gil/channel_algorithm.hpp

Add cast to explicitly indicate `val` promotion to at least 32-bit integer.
The arithmetic operations are performed on `int` of higher rank type.
Finally, since the result value is guaranteed to fit range of `8/16-bit` result integer type, it is safe to cast.
This should make it clearer for a reader that subtleties of implicit promotions and conversions have been considered.
Refines #74

Improve casts in channel_convert_from_unsigned (refines PR #74)

---

.appveyor.yml
CMakeLists.txt
Jamfile

Add necessary flags to Boost.Build and CMake configurations as well as CI builds.
Following the agreement about [C++11 requirement in develop branch](https://lists.boost.org/boost-gil/2018/04/0015.php), Boost.GIL now officially requires compiler with support for C++11 or later.

Require C++11 or later

---

include/boost/gil/gil_concept.hpp

Clean up old MSVC cruft.
Follows #77

Remove #if _MSC_VER > 1310 as always true since switch to C++11

---

include/boost/gil/utilities.hpp

Add divisor check to `point2<T>::operator/=`, if Zero do nothing.
This **hack** helps to avoid compiler warnings without polluting the source with pragmas.

Test float-point divisor for less/greater-than Zero

---

CMakeLists.txt
Jamfile
test/CMakeLists.txt
test/Jamfile
test/channel/CMakeLists.txt
test/channel/Jamfile
test/channel/TODO.md
test/channel/algorithm_channel_arithmetic.cpp
test/channel/algorithm_channel_convert.cpp
test/channel/algorithm_channel_invert.cpp
test/channel/algorithm_channel_multiply.cpp
test/channel/algorithm_channel_relation.cpp
test/channel/channel_concepts.cpp
test/channel/channel_test_fixture.cpp
test/channel/channel_test_fixture.hpp
test/channel/channel_traits.cpp
test/channel/scoped_channel_value.cpp
test/gil_test_common.hpp

Motivation:
- state clearly what is covered with tests without reading non-trivial code
- avoid cleverness - tests should be no-brainer
- get closer to one test case targets one feature/beaviour with one check
- replace obscure `throw std::exception` with diagnostics that are actually
useful to pin-point failure cause and location - makes CI logs useful.
- allow to select and run specific tests
- make tests maintenance easy, quick and fun
Propose new structure of tests that reflects the previous tests hierarchy,
but organizes channel tests in `test/channel` directory with test programs
each covering specific library feature (or set of closely related features).
The refactored tests cover 100% of checks from the old `channel.cpp`,
plus it refines or adds a bunch more.
NOTE: old …

Refactor single-program channel test to Boost.Test suites and cases

---

include/boost/gil/channel_algorithm.hpp

Little C++11 refactoring, a step towards limiting Boost libraries as GIL dependency.

Replace boost::integer_traits with std::numeric_limits

---

include/boost/gil/promote_integral.hpp
test/CMakeLists.txt
test/Jamfile
test/promote_integral.cpp

Copied from Boost.Geometry, including original tests, with some non-functional modifications explained in the comments.
The utility can be used where it is important to avoid integer overflow.
Files copied from Boost.Geometry include:
- [promote_integral.hpp](https://github.com/boostorg/geometry/blob/494045809e1ce639c8aa8d77b78e59564a4eeda3/include/boost/geometry/util/promote_integral.hpp)
- [test/util/promote_integral.cpp](https://github.com/boostorg/geometry/blob/ba9117b37ee7194dba547bade9c0f1f24c9dea98/test/util/promote_integral.cpp)

Add promote_integral metafunction

---

include/boost/gil/promote_integral.hpp
test/promote_integral.cpp

Non-functional refactoring of `promote_integral` added in #91
#91

Replace some of Boost.MPL and Boost.TypeTraits with C++11 equivalents

---

include/boost/gil/channel_algorithm.hpp

This should help to avoid UB due to possible signed integer overflows, for minimum/maximum of input channel domain.
Fixes #89
I have verified locally that this patch fixes the `channel_invert` algorithm test failure when building with clang 5.0 and `variant=release`, which originally has been failing on https://circleci.com/gh/boostorg/gil/966  Once this PR is merged, the clang 5.0 build job on CircleCI should have been fixed as well.
```
====== BEGIN OUTPUT ======
Running 30 test cases...
/mnt/d/boost.wsl/libs/gil/test/channel/algorithm_channel_invert.cpp(22): 
error: in "channel_value<int>":
check gil::channel_invert(f.min_v_) == f.max_v_ has failed [-1 != 2147483647]
/mnt/d/boost.wsl/libs/gil/test/channel/algorithm_channel_invert.cpp(22):
error: in "channel_reference<int>":
check …
```

Use promote_integral in channel_invert algorithm

---

.ci/blacklist.supp
.ci/build-and-test.sh
.gitattributes
.travis.yml
Jamfile

(NOTE: _Assigned to self - if accepted, I'd like to merge myself. Thanks._)
The build variants enable group of checks offered by clang
[UndefinedBehaviorSanitizer](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html) detector.
Add [sanitizers suppression](https://clang.llvm.org/docs/SanitizerSpecialCaseList.html) file in `.ci/blacklist.supp` based on copy of [the file from Boost.Beast](https://github.com/boostorg/beast/blob/develop/tools/blacklist.supp).
Update Travis CI:
- Add build jobs for each of the three new UBSan variants.
- Display COMPILER and VARIANT first as these two are most important
details while inspecting the build matrix
(TOOLSET can be derived from COMPILER).
-----
I've built the UBSan variants and there are issues - to be checked/fixed after this is merged.

Add Boost.Build variants for UBSan-enabled builds

---

.travis.yml

(NOTE: _Assigned to self - if accepted, I'd like to merge myself. Thanks._)
`tools/boostdep/depinst/depinst.py` helper automatically calculates maximum set of required Boost libraries, based on `#include`-s.
Manual listing should help to control any new additions and prevent introduction of unwanted dependencies.

[travis] List required Boost libraries explicitly

---

include/boost/gil/channel.hpp
include/boost/gil/gil_config.hpp

(NOTE: _Assigned to self - if accepted, I'd like to merge myself. Thanks._)
Rename `GIL_NONWORD_POINTER_ALIGNMENT_SUPPORTED`   to `BOOST_GIL_CONFIG_HAS_UNALIGNED_ACCESS`.
Undefine `BOOST_GIL_CONFIG_HAS_UNALIGNED_ACCESS` by default and document it.
If defined, issue warning or error, depending on target platform.
This changes how `packed_channel_reference_base`-based channels perform access - aligned memory access by default.
This also fixes undefined behavior detected by UBSan in some test cases.
-----
Accessing a misaligned pointer results in undefined behavior and causes numerous [UBSan sanitizer run-time errors](https://travis-ci.org/boostorg/gil/jobs/395130083) on Travis CI (and locally too).
For example:
```
channel.hpp:348:70: runtime error: reference binding to misaligned address …
```

Disable unaligned pointer access

---

.appveyor.yml
.travis.yml

(This change has already been reviewed as part of #101)
Group list of deps for easy identification of direct ones.
Add --quiet option to git submodule commands on Travis CI.
#101

[appveyor] List required Boost libraries explicitly

---

.travis.yml
include/boost/gil/extension/numeric/kernel.hpp
include/boost/gil/io/base.hpp
include/boost/gil/io/bit_operations.hpp

Replace `boost::array` with C++11 `std::array`.

Remove dependency on boost::array

---

.travis.yml
include/boost/gil/extension/io/pnm/detail/write.hpp

Replace `lexical_cast` with C++11 `std::to_string` function.

Remove dependency on boost::lexical_cast

---

.travis.yml
include/boost/gil/extension/io/jpeg/detail/reader_backend.hpp
include/boost/gil/extension/io/jpeg/detail/writer_backend.hpp
include/boost/gil/extension/io/png/detail/base.hpp
include/boost/gil/extension/io/raw/detail/device.hpp
include/boost/gil/extension/io/tiff/detail/device.hpp
include/boost/gil/extension/io/tiff/detail/write.hpp
include/boost/gil/io/device.hpp
include/boost/gil/io/scanline_read_iterator.hpp

Replace boost::shared_ptr with C++11 std::shared_ptr.

Remove dependency on Boost.SmartPtr

---

.travis.yml

Currently, UBSan integer checks report several false positives due to unsigned integer overflows (well-defined):
Instead of hiding them completely, keep them displayed on the matrix until we decide how to handle.
For example, [build 375.9](https://travis-ci.org/boostorg/gil/jobs/396282494#L1181).
This has been discussed and agreed with @stefanseefeld, this should help us to keep the `master`-branch to be consistent with the one for `develop`. See #109 for further discussion.

[travis] Allow failures for variant=ubsan_integer

---

.circleci/config.yml

CircleCI 2.0 does not yet support branch filtering per workflow.
-----
This only rationalizes CircleCI setup to avoid unnecessary use of resources for non-builds (eg. for `gh-pages` branch).
This should also be merged into `master` for best effect.

[circleci] Allow only master and develop branches for all build jobs

---

doc/tutorial.rst

This video lecture was originally published at
https://stlab.adobe.com/gil/presentation/index.htm
Boost.GIL maintainers received agreement from Lubomir Bourdev to copy and preseve the original video:
_Agreement to capture Lubomir's video lecture and PDFs_, https://lists.boost.org/boost-gil/2018/06/0032.php
The lecture has also been archived by Sean Parent (Adobe) at https://youtu.be/RjNz_sl-eXk
Thanks to Sean for sharing .MOV file he captured from the original server.

[doc] Embed original video by Lubomir Bourdev in Tutorial

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

This documents a simple PR protocol with requirement that all new PRs should be submitted from a topic branch based on `develop`, and never on `master`.

Require PRs to be based on develop, and never on master

---

CMakeLists.txt
example/CMakeLists.txt
io/test/CMakeLists.txt

Several minor fixes for CMake setup of GIL examples and IO tests.
This does NOT address #40 - examples still may not compile

Apply minor fixes to CMake configuration

---

include/boost/gil/image_view.hpp
test/Jamfile
test/image_view/CMakeLists.txt
test/image_view/Jamfile
test/image_view/image_view_concepts.cpp

* Apply patch from https://svn.boost.org/trac10/ticket/8896
* Add compile-time test of `RandomAccessNDImageViewConcept`
* Confirms the reported failure (tested with GCC 7.3 and clang 5.0)
* Verifies correctness of the patch
- Boost version (see `<boost/version.hpp>`): 1.68
- Compiler version: GCC 4.2 or later, clang 3.8 or later
- Build settings:
https://svn.boost.org/trac10/ticket/8896
-----
The MWE to reproduce the problem originally posted in the Trac ticket:
```
mloskot@xenial:~/tmp$ cat gil_ticket_8896.cpp
#include <iostream>
#include <boost/gil/gil_all.hpp>
using namespace boost;
namespace bg = boost::gil;
int main(int argc, char **argv)
{
bg::gray8_image_t img(2,2);
bg::gray8_view_t vw(bg::view(img));
bg::gray8_view_t::point_t p(0,0); …
```

Add missing template keyword prior to dependent name axis_iterator (Trac 8896)

---

include/boost/gil/io/device.hpp

The `num_elements` is used only in `assert`, so it is unused in optimised builds.

Fix warning about assigned but unused variable num_elements

---

example/dynamic_image.cpp

Reminder: Boost.GIL 2.2 released in Boost 1.67 has completely reimplemented I/O extensions.
There still may be examples that no longer compiler.
- Compiler version: GCC 8.x

Update example/dynamic_image.cpp after IO reimplentation

---

include/boost/gil/extension/io/jpeg/detail/reader_backend.hpp

The previous name is too generic and prone to variable shadowing, causing compilation warnings (eg. vector named buffer in JPEG-s `reader::read_rows` method).
- Compiler version: GCC 8.x

Rename JPEG-s reader_backend::buffer member array to buffer_

---

Jamfile
doc/Jamfile
example/Jamfile
io/doc/Jamfile
io/test/Jamfile
numeric/doc/Jamfile
numeric/test/Jamfile
numeric/test/numeric.cpp
numeric/test/test.cpp
test/Jamfile
test/channel/Jamfile
test/image_view/Jamfile
toolbox/doc/Jamfile
toolbox/test/Jamfile

Rename `Jamfile.v2` to `Jamfile` - BBv1 is dead.
Remove `numeric/test/test.cpp` as redundant.

Simplify and clean up Jamfiles

---

Jamfile
example/Jamfile
example/affine.cpp
example/dynamic_image.cpp
example/histogram.cpp

Update examples to catch up with recent changes and ensure they both
compile without errors (using GCC 5).
* #40
- [x ] All CI builds and checks have passed
-----
ATM, examples are not compiled by default on CI-s but I've verified these compile locally with GCC 5.

Add first batch of examples to Jamfile

---

include/boost/gil/extension/toolbox/color_spaces/hsv.hpp

Trick compiler by using `>=` instead of `==`, where LHS color is guaranteed to never be greater than RHS color value.
- Compiler version: GCC 8.x

Fix warning: comparing floating point with == is unsafe

---

include/boost/gil/extension/toolbox/metafunctions/get_num_bits.hpp

Previously used `mpl::int_` assumes signed integer, while `sizeof(T)` is unsigned and compiler issues warning.
- Compiler version: GCC 8.x

Base get_num_bits metafunction for T on mpl::size_t instead of mpl::int_

---

test/promote_integral.cpp

The explicit casts help to avoid warnings when integer types smaller than `int` are implicitly converted during arithmetic operations.
-----
This should fix warnings during compilation of the test:
```
promote_integral.cpp: In instantiation of ‘static void test_max_values<Integral, Promoted, Signed>::apply() [with Integral = signed char; Promoted = short int; bool Signed = true]’:
promote_integral.cpp:157:65:   required from ‘static void test_promote_integral<PromoteUnsignedToUnsigned>::apply(const string&) [with Type = signed char; ExpectedPromotedType = short int; bool PromoteUnsignedToUnsigned = false; std::__cxx11::string = std::__cxx11::basic_string<char>]’
promote_integral.cpp:222:45:   required from ‘static void test_promotion<T, PromoteUnsignedToUnsigned, …
```

Add casts to avoid warnings due to implicit integral promotions

---

include/boost/gil/metafunctions.hpp

https://svn.boost.org/trac10/ticket/2979 description:
> The description of the metafunction boost::gil::image_is_basic says that
> it will return mpl::true_ if the image uses a basic view and
> std::allocator<unsigned char>, however the implementation returns true
> for any kind images that use any kind of allocator.

Correct description of image_is_basic metafunction (Trac 2979)

---

include/boost/gil/io/bit_operations.hpp
include/boost/gil/io/conversion_policies.hpp
include/boost/gil/io/error.hpp
include/boost/gil/io/path_spec.hpp
include/boost/gil/io/read_and_convert_image.hpp
include/boost/gil/io/read_and_convert_view.hpp
include/boost/gil/io/read_image.hpp
include/boost/gil/io/read_image_info.hpp
include/boost/gil/io/read_view.hpp
include/boost/gil/io/row_buffer_helper.hpp
include/boost/gil/io/scanline_read_iterator.hpp
include/boost/gil/io/write_view.hpp
include/boost/gil/premultiply.hpp

Make core and io headers self-contained.
Required by test to verify headers are self-contained in #147.
-----
The missing headers revealed using the test from #147 using GCC 5.5 locally.

Add #include directives with missing headers

---

include/boost/gil/color_base_algorithm.hpp
include/boost/gil/concepts.hpp
test/pixel.cpp

An attempt to clean up several warnings picked randomly:
* Replace unsigned with signed for int as compile-time index.
* Use GCC pragma to disable `-Wconversion` and `-Wfloat-equal`.
* Add explicit conversion of arithmetic result to expected result type. 
There also have been superfluous trailing whitespaces auto-trimmed (`.editorconfig` in action).

Fix some gcc warnings

---

.appveyor.yml
.editorconfig
.travis.yml
test/Jamfile
test/self_contained_header.cpp

For each header, a translation unit is generated along with corresponding compile target.
Currently, only `boost/gil/*.hpp` and `boost/gil/io/* headres` are included.
On CI services, compile self_contained_headers targets only if `TEST_HEADERS` environment variable is set. This is to avoid build timeouts due to CI services limits.
When running b2 locally, the tests are compiled by default.
-----
NOTE: The self-contained headers tests are built by default. There will be compilation errors due to actual 'broken' headers! Obviously, those need to be fixed via dedicated PRs/commits.
* #148

Add test to verify headers are self-contained

---

include/boost/gil/algorithm.hpp
test/Jamfile
test/algorithm/Jamfile
test/algorithm/std_fill.cpp

Add minimal test for the `std::fill` and `boost::array` or `std::array` as pixel type.
* https://svn.boost.org/trac10/ticket/7189
-----
https://svn.boost.org/trac10/ticket/7189 description:
> The following does not compile because it cannot be resolved whether a call
> to `boost::range::fill_n` or `std::fill_n` is correct
> 
> ```
> #include <boost/array.hpp>
> #include <boost/gil/image_view.hpp>
> #include <boost/gil/image.hpp>
> #include <boost/gil/typedefs.hpp>
> #include <boost/range/algorithm/fill_n.hpp>
> namespace gil = boost::gil;
> int main( int argc, char** argv)
> {
>     gil::image<boost::array<float,2> > img;
>     std::fill( gil::view(img).begin(), gil::view(img).end(), boost::array<float,2>() );
> }
> ```
> 
> Error:
> 
> ```
> [100%] Building CXX object …
```

Fix conflict with std::fill_n and boost::range::fill_n (Trac 7189)

---

include/boost/gil.hpp
include/boost/gil/extension/dynamic_image/any_image_view.hpp
include/boost/gil/extension/dynamic_image/image_view_factory.hpp
include/boost/gil/image_view_factory.hpp
include/boost/gil/io/typedefs.hpp
include/boost/gil/iterator_from_2d.hpp
include/boost/gil/locator.hpp
include/boost/gil/point.hpp
include/boost/gil/typedefs.hpp
include/boost/gil/utilities.hpp

The point belongs to core basic concepts in GIL, not an optional utility. The tutorial starts with description of point.
Such core concepts are defined in dedicated headers which is quite a useful convention that also makes the code structure clearer.
Clean up point.hpp formatting (eg. respect line length limit).
------
@stefanseefeld suggested on Gitter:
> why don't we use point<> rather than point2<> ?
> Given that this is not a generic "Point" class, but one specific to (2D) image processing, the '2' is implicit.
> I'd thus suggest we rename it to point, and then add a using point2 = point; for backward compatibility.

Extract point2<T> from utilities.hpp to point.hpp

---

.travis.yml

Currently, we are experiencing UBSan builds failures due to issues in Boost.Function version attached to Boost super-project.
Build UBSan with b2 `visibility=global` instead of default `hidden`.
Detailed discussions at:
- https://github.com/boostorg/function/pull/29
- https://lists.boost.org/boost-gil/2018/10/0100.php
Note, we are switching temporarily and we should switch back to testing against Boost super-project master branch - a stable Boost version closest to the next release state.
-----
I've got Travis CI for my fork at https://travis-ci.org/mloskot/gil which starts and completes the builds much quicker than for the org at https://travis-ci.org/boostorg/gil/

[travis] Switch Boost super-project to develop branch

---

include/boost/gil/point.hpp
test/point/point.cpp

The free variants of `operator/` and `operator*` now yield new type of `point<T>` with `T` promoted to type common for both operands.
Add missing member `operator*=`, for symmetry.
Add template function `iround(point<T>)` as no-op sink for `point` specialisations for `T` of integer types.
Add explicit casts of arithmetic intermediate results to avoid compilation warnings.
Replace redundant `point<T>` construction in return statement with uniform initialization.
Add `static_assert` validating range of `axis_value` integer template parameter.
Update `test/point/point.cpp` with basic checks of all `point<T>` members.
Fixes #153

Fix point<T> divide and multiply to not to hardcode result as point<double>

---

toolbox/test/indexed_image_test.cpp

Let's give toolbox some love.
----
By the way, apart from the expression nonsense, there is also testing `uint8_t` for values of `256` 
```
toolbox/test/indexed_image_test.cpp: In lambda function:
toolbox/test/indexed_image_test.cpp:40:36: warning: comparison is always false due to limited range of data type [-Wtype-limits]
i = (i == 256) ? 0 : (i + 1);
^
toolbox/test/indexed_image_test.cpp: In lambda function:
toolbox/test/indexed_image_test.cpp:51:36: warning: comparison is always false due to limited range of data type [-Wtype-limits]
i = (i == 256) ? 0 : (i + 1);
^
```
Now, is the `uint8_t` supposed to be larger or `256` decreased to `255`?

Fix undefined behaviour due to unsequenced side effects of same scalar

---

include/boost/gil/extension/toolbox/color_spaces/ycbcr.hpp
include/boost/gil/extension/toolbox/image_types/subchroma_image.hpp

Copy `boost::algorithm::clamp` to where it was solely used in Toolbox.
Add `subchroma_image.cpp` missing from build target of Toolbox test.

Remove dependency on boost/algorithm/clamp.hpp

---

include/boost/gil/bit_aligned_pixel_iterator.hpp
include/boost/gil/cmyk.hpp
include/boost/gil/color_base.hpp
include/boost/gil/color_convert.hpp
include/boost/gil/extension/dynamic_image/algorithm.hpp
include/boost/gil/extension/dynamic_image/apply_operation.hpp
include/boost/gil/extension/dynamic_image/apply_operation_base.hpp
include/boost/gil/extension/toolbox/color_spaces/hsl.hpp
include/boost/gil/extension/toolbox/color_spaces/hsv.hpp
include/boost/gil/extension/toolbox/color_spaces/lab.hpp
include/boost/gil/extension/toolbox/color_spaces/xyz.hpp
include/boost/gil/extension/toolbox/color_spaces/ycbcr.hpp
include/boost/gil/extension/toolbox/metafunctions/channel_view.hpp
include/boost/gil/image.hpp
include/boost/gil/packed_pixel.hpp
include/boost/gil/pixel.hpp
include/boost/gil/pixel_iterator.hpp
include/boost/gil/pixel_iterator_adaptor.hpp
include/boost/gil/planar_pixel_reference.hpp
include/boost/gil/position_iterator.hpp
include/boost/gil/rgb.hpp
include/boost/gil/rgba.hpp
include/boost/gil/step_iterator.hpp
include/boost/gil/virtual_locator.hpp

PowerShell script used to perform the trimming:
```powershell
Get-ChildItem -Recurse -Include @("*.cpp", "*.hpp") |
ForEach-Object { (Get-Content $_.FullName)
| Foreach {$_.TrimEnd()} | Set-Content $_.FullName }
```

Trim trailing whitespaces in all source code files

---

include/boost/gil/concepts/channel.hpp
include/boost/gil/concepts/color.hpp
include/boost/gil/concepts/color_base.hpp
include/boost/gil/concepts/detail/type_traits.hpp
include/boost/gil/concepts/image.hpp
include/boost/gil/concepts/image_view.hpp
include/boost/gil/concepts/pixel.hpp
include/boost/gil/concepts/pixel_based.hpp
include/boost/gil/concepts/pixel_dereference.hpp
include/boost/gil/concepts/pixel_iterator.hpp
include/boost/gil/concepts/pixel_locator.hpp
include/boost/gil/concepts/point.hpp

Replace `typedef` with using declaration.
Replace complex return type declared for functions with trailing return type and `auto`.
Format complex metaprogramming constructs in clear and readable way.
Remove superfluous `public` access specifier from `struct` inheritance.
Rename ambiguous type aliases.
Make template parameters
- upper-case (if initials e.g. CS)
- camel-case if multi-word (e.g. ColorSpace).
Part of ongoing extensive modernisation, reformatting and clean-up prior being applied, also as preparation for overhaul removing/replacing with C++11 Boost.MPL, Boost.TypeTraits and other tightly coupled Boost libraries as dependencies.

Reformat boost/gil/concepts/*.hpp to limit line length to 90 characters

---

include/boost/gil/extension/numeric/algorithm.hpp
include/boost/gil/extension/numeric/channel_numeric_operations.hpp
include/boost/gil/extension/toolbox/color_spaces/hsl.hpp
include/boost/gil/extension/toolbox/color_spaces/hsv.hpp
include/boost/gil/extension/toolbox/color_spaces/lab.hpp
include/boost/gil/extension/toolbox/color_spaces/xyz.hpp
include/boost/gil/extension/toolbox/color_spaces/ycbcr.hpp
include/boost/gil/extension/toolbox/image_types/indexed_image.hpp

Follows up the improvements in the self-contained headers test in https://github.com/boostorg/gil/commit/1075967712afd85b52dae49fb996a664632a98c5, that revealed issues in the extensions.

Add missing #include-s to ensure self-contained headers

---

include/boost/gil/extension/toolbox/color_spaces/ycbcr.hpp
include/boost/gil/extension/toolbox/image_types/subchroma_image.hpp
toolbox/test/CMakeLists.txt
toolbox/test/Jamfile
toolbox/test/fabscript
toolbox/test/subchroma_image.cpp

Add missing typenamei in mpl::if_ condition result
Restore BOOST_CXX14_CONSTEXPR in boost::algorithm::clamp function
- apparently, GCC 5.5.0 does not compile it with C++11 constexpr.
Still not adding subchroma_image.cpp to toolbox test target input sources due to run-time failure.
Depends on #176

Fix compile-time bugs subchroma_image.hpp definions

---

include/boost/gil/extension/io/jpeg/detail/writer_backend.hpp

The reference to `writer<Device,jpeg_tag>` is clearly incorrect:
- writer has no members `init_device`, `empty_buffer`, `closed_buffer`
- if use of writer was correct there, it would require
`#include <boost/gil/extension/io/jpeg/detail/writer.hpp>`, but that
would impose cyclic-dependency between writer.hpp and writer_backend.hpp.
-----
How on earth it's never been noticed?! Is the fix actually correct or am I completely confused myself?
```
cmake --build . --target test_compile_headers
...
[ 15%] Building CXX object test/headers/CMakeFiles/test_header_extension-io-jpeg-write.dir/extension-io-jpeg-write.cpp.o
In file included from /mnt/d/boost.wsl/libs/gil/include/boost/gil/extension/io/jpeg/detail/write.hpp:13:0,
from /mnt/d/boost.wsl/libs/gil/include/boost/gil/extension/io/jpeg/write.hp …
```

Replace writer<Device,jpeg_tag> where writer_backend<Device,jpeg_tag> expected

---

doc/io.rst
include/boost/gil/extension/io/raw/tags.hpp
io/doc/io.qbk

Since [libraw](https://www.libraw.org/) is C++ library, not C, it is always built as C++ library.
The current `#include <libraw/libraw.h>` is this:
```
#ifndef BOOST_GIL_EXTENSION_IO_RAW_C_LIB_COMPILED_AS_CPLUSPLUS
extern "C" {
#endif
#include <libraw/libraw.h>
#ifndef BOOST_GIL_EXTENSION_IO_RAW_C_LIB_COMPILED_AS_CPLUSPLUS
}
#endif
```
if compiled without `BOOST_GIL_EXTENSION_IO_RAW_C_LIB_COMPILED_AS_CPLUSPLUS` defined, compiler throws errors:
```
$ VERBOSE=1 make test_header_extension-io-raw-detail-read
...
[100%] Building CXX object test/headers/CMakeFiles/test_header_extension-io-raw-detail-read.dir/extension-io-raw-detail-read.cpp.o
cd /mnt/d/boost.wsl/libs/gil/_build.gcc5/test/headers && /usr/bin/c++   -I/mnt/d/boost.wsl/libs/gil/include -I/mnt/d/boost.wsl/libs/gil/test -isystem …
```

Remove unnecessary extern C around libraw.h include

---

include/boost/gil/extension/io/bmp/detail/supported_types.hpp
include/boost/gil/extension/io/jpeg/detail/reader_backend.hpp
include/boost/gil/extension/io/jpeg/detail/supported_types.hpp
include/boost/gil/extension/io/png/detail/supported_types.hpp
include/boost/gil/extension/io/pnm/detail/supported_types.hpp
include/boost/gil/extension/io/pnm/detail/write.hpp
include/boost/gil/extension/io/raw/detail/device.hpp
include/boost/gil/extension/io/raw/detail/supported_types.hpp
include/boost/gil/extension/io/targa/detail/supported_types.hpp
include/boost/gil/extension/io/tiff/detail/device.hpp
include/boost/gil/extension/io/tiff/detail/supported_types.hpp
include/boost/gil/extension/io/tiff/detail/writer_backend.hpp

Missing headers revealed by compilation of self-contained header tests.
-----
All self-container header tests compile on Linux with GCC 5.5 (configured with CMake):
```
$ mkdir _build.gcc5
$ cd _build.gcc5/
$ cmake -DBoost_ARCHITECTURE=-x64 ..
$ make test_compile_headers
[  1%] Built target test_header_io-error
[  3%] Built target test_header_virtual_locator
[  4%] Built target test_header_typedefs
[  4%] Built target test_header_step_iterator
[  6%] Built target test_header_rgb
[  6%] Built target test_header_promote_integral
[  6%] Built target test_header_premultiply
[  7%] Built target test_header_position_iterator
[  7%] Built target test_header_pixel_iterator
[  9%] Built target test_header_packed_pixel
[ 11%] Built target test_header_iterator_from_2d
[ 11%] Built target …
```

Include missing headers across boost/gil/extension/io

---

.clang-tidy
test/image.cpp

Used clang-tidy 7.0 with the command:
```
run-clang-tidy.py \
-header-filter='boost\/gil\/.*'
-checks='-*,modernize-use-override' -fix
```
- #180

Apply clang-tidy modernize-use-override

---

test/headers/CMakeLists.txt

Rename target `test_compile_headers` to `test_headers_self_contained`.
Add target `test_headers_all_in_one`
- Currently tests headers of core, `concepts` and `io`.
-----
Note, none of the headers tests are configured to build on the CI builds or the regression builds.
When CMake configures build locally, all those tests are enabled.

[cmake] Add test with all headers included in one TU

---

include/boost/gil/extension/io/png/detail/base.hpp

Replace `png_structp` and `png_infop` aliases with regular pointers to to prevent type qualifiers ignored on function return type.
-----
By the way, the alias is defined as `typedef png_struct FAR * png_structp;` and I think we are safe to ignore the `FAR` qualifier :)

Fix const on return type not applied to pointee type of typedef

---

include/boost/gil/extension/numeric/channel_numeric_operations.hpp
include/boost/gil/extension/numeric/pixel_numeric_operations.hpp

`std::unary_function` and `std::binary_function` are deprecated in C++11 and removed in C++17. I think they are safe to remove since C++11 is required anyway.

Remove deprecated unary/binary_function.

---

include/boost/gil/extension/numeric/algorithm.hpp
include/boost/gil/extension/numeric/convolve.hpp
include/boost/gil/extension/numeric/kernel.hpp
include/boost/gil/extension/numeric/sampler.hpp

Run clang-tidy 7.0 with `-checks='-*,modernize-use-using' -fix` against
single TU with `#include <boost/gil/extension/numeric/*.hpp>`.
Manually refactor numerous `typedef`-s
- where missed by modernize-use-using check, not uncommon
- in code snippets in comments
Outcome is that searching for lower-case whole word `typedef`
in all the `extension/numeric/*.hpp` should return no matches,
- #192
- #193
- #195

Apply clang-tidy modernize-use-using to extension/numeric

---

include/boost/gil/io/base.hpp
include/boost/gil/io/conversion_policies.hpp
include/boost/gil/io/device.hpp
include/boost/gil/io/dynamic_io_new.hpp
include/boost/gil/io/get_read_device.hpp
include/boost/gil/io/get_reader.hpp
include/boost/gil/io/get_write_device.hpp
include/boost/gil/io/get_writer.hpp
include/boost/gil/io/make_backend.hpp
include/boost/gil/io/make_reader.hpp
include/boost/gil/io/read_and_convert_image.hpp
include/boost/gil/io/read_and_convert_view.hpp
include/boost/gil/io/read_image.hpp
include/boost/gil/io/read_view.hpp
include/boost/gil/io/reader_base.hpp
include/boost/gil/io/row_buffer_helper.hpp
include/boost/gil/io/scanline_read_iterator.hpp
include/boost/gil/io/typedefs.hpp
include/boost/gil/io/write_view.hpp

Run clang-tidy 7.0 with `-checks='-*,modernize-use-using' -fix` against single TU with `#include <boost/gil/io/*.hpp>`.
Manually refactor numerous `typedef`-s
- where missed by modernize-use-using check, not uncommon
- in code snippets in comments
Outcome is that searching for lower-case whole word `typedef` in all `io/*.hpp` should return no matches.
- #192
- #193

Apply clang-tidy modernize-use-using to io

---

example/interleaved_ptr.cpp
example/mandelbrot.cpp
example/packed_pixel.cpp
example/x_gradient.cpp

Following release of the new IO in Boost 1.68, the examples stopped compiling.
Fixes #40
- ~[ ] All CI builds and checks have passed~ Currently, CI-s do not build examples

Fix examples to make them compile again

---

example/convolution.cpp
include/boost/gil/extension/numeric/convolve.hpp

Fix hard-wired use of Boost.Array static_size member

---

include/boost/gil/extension/io/bmp/detail/read.hpp
include/boost/gil/extension/io/bmp/detail/scanline_read.hpp
include/boost/gil/extension/io/pnm/detail/read.hpp
include/boost/gil/extension/io/pnm/detail/scanline_read.hpp
include/boost/gil/extension/io/pnm/detail/write.hpp
include/boost/gil/extension/io/tiff/detail/scanline_read.hpp
include/boost/gil/io/bit_operations.hpp

Replace Boost.MPL boolean constants with C++11 equivalents.
Replace `throw()` with `noexcept`.
Replace empty constructor body with `default`.
Rename private class members to avoid leading underscore (too easy to confuse as reserved identifier).
Tidy up with compact formatting.
- #202

Remove Boost.Bind from io

---

include/boost/gil/extension/dynamic_image/algorithm.hpp
include/boost/gil/extension/dynamic_image/apply_operation.hpp

Replace `boost::bind` with `std::bind` from C++11.
Move template parameter comments to Doxygen `\tparam`-s, so they are captured as proper documentation.
Tidy up code formatting.
- #203

Remove Boost.Bind from extension/dynamic_image

---

.azure-pipelines.yml
.ci/azure-pipelines/steps-check-cmake.yml
.ci/azure-pipelines/steps-cmake-build-and-test.yml
.ci/azure-pipelines/steps-install-boost.yml
.ci/azure-pipelines/steps-install-conan.yml

Configuration summary:
- Linux (GCC 5.4), Windows (VS2017), Mac OS (clang 4.0)
- Boost 1.68 built with variant=release
- Boost.GIL built and tested using CMake w/ CMAKE_BUILD_TYPE=Release
- Basic setup of GIL IO extension dependencies is in place,
using .deb packages or Conan.
- Build without GIL IO extension tests due to issues in CMake
configuration, not related to Azure Pipelines.
- Closes #188

Add configuration for CI builds with Azure Pipelines

---

toolbox/test/indexed_image_test.cpp

Since GIL requires minimum C++11, this was a _dead code_.

Remove pre-C++11 version of test pixels generator

---

.appveyor.yml
.travis.yml
include/boost/gil/algorithm.hpp
include/boost/gil/bit_aligned_pixel_reference.hpp
include/boost/gil/channel.hpp
include/boost/gil/channel_algorithm.hpp
include/boost/gil/color_base.hpp
include/boost/gil/color_base_algorithm.hpp
include/boost/gil/extension/dynamic_image/dynamic_at_c.hpp
include/boost/gil/extension/dynamic_image/variant.hpp
include/boost/gil/extension/io/bmp/detail/read.hpp
include/boost/gil/extension/io/png/detail/base.hpp
include/boost/gil/extension/io/tiff/detail/read.hpp
include/boost/gil/extension/numeric/algorithm.hpp
include/boost/gil/extension/numeric/convolve.hpp
include/boost/gil/extension/numeric/kernel.hpp
include/boost/gil/image_view_factory.hpp
include/boost/gil/io/device.hpp
include/boost/gil/io/reader_base.hpp
include/boost/gil/iterator_from_2d.hpp
include/boost/gil/locator.hpp
include/boost/gil/packed_pixel.hpp
include/boost/gil/pixel_iterator.hpp
include/boost/gil/planar_pixel_iterator.hpp
include/boost/gil/virtual_locator.hpp
numeric/test/numeric.cpp
test/pixel.cpp
test/pixel_iterator.cpp
toolbox/test/indexed_image_test.cpp

Add `#include <boost/assert.hpp>` where necessary.
Apply minor clean-up near the macro replacements.
Closes #96

Replace assert() macro with BOOST_ASSERT() macro

---

example/interleaved_ptr.cpp
example/interleaved_ptr.hpp
example/interleaved_ref.hpp
example/mandelbrot.cpp
example/packed_pixel.cpp
example/x_gradient.cpp

Run clang-tidy 7.0 with `-checks='-*,modernize-use-using' -fix` against TU-s of examples.
Manually refactor numerous typedef-s where missed by `modernize-use-using` check, not uncommon in code snippets in comments.
Outcome is that searching for lower-case whole word `typedef` in sources of all the tests should return only handful of matches in `boost/gil/extension/dynamic_image/apply_operation_base.hpp`
- #192
- #193
- #195
- #196
- #197
- #198
-----
@stefanseefeld Nothing exciting to review though :)

Apply clang-tidy modernize-use-using to all examples

---

doc/design_guide.rst
doc/doxygen/design_guide.dox
doc/doxygen/tutorial.dox
doc/tutorial.rst
example/mandelbrot.cpp
include/boost/gil/bit_aligned_pixel_iterator.hpp
include/boost/gil/bit_aligned_pixel_reference.hpp
include/boost/gil/channel.hpp
include/boost/gil/color_base_algorithm.hpp
include/boost/gil/extension/toolbox/image_types/subchroma_image.hpp
include/boost/gil/image_view_factory.hpp
include/boost/gil/io/base.hpp
include/boost/gil/metafunctions.hpp
include/boost/gil/packed_pixel.hpp
include/boost/gil/pixel.hpp
include/boost/gil/planar_pixel_reference.hpp
include/boost/gil/premultiply.hpp
include/boost/gil/utilities.hpp
io/test/mandel_view.hpp
test/channel.cpp
test/channel/channel_concepts.cpp
test/image.cpp

Tidy up formatting of refactored parts of code.

Replace BOOST_STATIC_CONSTANT with constexpr

---

.appveyor.yml
.travis.yml
example/histogram.cpp
include/boost/gil/extension/dynamic_image/reduce.hpp
include/boost/gil/extension/dynamic_image/variant.hpp
include/boost/gil/extension/numeric/resample.hpp
include/boost/gil/io/base.hpp
test/image.cpp
test/recreate_image.cpp

Replace with `std::bind` and C++11 lambda functions.
The two Boost libraries should no longer be a direct dependency of Boost.GIL.

Remove uses of Boost.Bind and Boost.Lambda

---

.appveyor.yml
.travis.yml
include/boost/gil/extension/io/bmp/detail/scanline_read.hpp
include/boost/gil/extension/io/pnm/detail/scanline_read.hpp
include/boost/gil/extension/io/tiff/detail/scanline_read.hpp

Remove uses of `boost::mem_fn` (missing from Bind.Bind removal in #212).

Remove uses of Boost.Function

---

CONTRIBUTING.md

This update does not inroduce any major modification to the current
workflow, it adds a more formal description of it.
With minor updates, copied from CoreFX guidelines:
https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/contributing.md
-----
@stefanseefeld AFAIR, we discussed usefulness of the CoreFx guidelines on Gitter and your recent post, https://lists.boost.org/Archives/boost/2019/01/244851.php, reminded me about this.

Update CONTRIBUTING.md with PRs do's and don'ts [ci skip]

---

test/channel/algorithm_channel_arithmetic.cpp
test/channel/algorithm_channel_relation.cpp

Fixes at least two warnings issued by channel tests due to
comparison of unsigned channel value with signed integer 1:
```
../../boost/test/tools/assertion.hpp:72:13:
warning: comparison between signed and unsigned
integer expressions [-Wsign-compare]
```
- Compiler version: GCC 5.5
- Build settings: `<toolset>gcc:<cxxflags>"-std=c++11"`
------
GCC warnings this PR fixes are:
```
In file included from ../../boost/test/test_tools.hpp:53:0,
from ../../boost/test/unit_test.hpp:18,
from test/gil_test_common.hpp:24,
from test/channel/algorithm_channel_arithmetic.cpp:14:
../../boost/test/tools/assertion.hpp: In instantiation of ‘static boost::test_tools::assertion::op::EQ<Lhs, Rhs, Enabler>::result_type boost::test_tools::assertion::op::EQ<Lhs, Rhs, …
```

Fix GCC -Wsign-compare warning in tests

---

toolbox/test/channel_type.cpp
toolbox/test/indexed_image_test.cpp

Fixes at least three warnings issued by in the toolbox tests:
```
warning: typedef (...) locally defined
but not used [-Wunused-local-typedefs]
```
- Compiler version: GCC 5.5
- Build settings: `<toolset>gcc:<cxxflags>"-std=c++11"`
-------
```
toolbox/test/channel_type.cpp: In member function ‘void toolbox_tests::channel_type_test::test_method()’:
toolbox/test/channel_type.cpp:27:69: warning: typedef ‘using channel_t = boost::lazy_enable_if_c<true, boost::gil::gen_chan_ref<unsigned int, boost::mpl::vector4_c<unsigned int, 4u, 4u, 4u, 4u>, boost::gil::layout<boost::mpl::vector3<boost::gil::red_t, boost::gil::green_t, boost::gil::blue_t> >, true> >::type’ locally defined but not used [-Wunused-local-typedefs]
using channel_t = channel_type<image_t::view_t::reference>::type;
^
```
``` …
```

Fix GCC -Wunused-local-typedefs warning in toolbox tests

---

toolbox/test/channel_view.cpp
toolbox/test/indexed_image_test.cpp

Fixes at least eight warnings issued by in the toolbox tests:
`warning: variable (...) set but not used [-Wunused-but-set-variable]`
Add new or improve existing `BOOST_TEST` checks.
- Compiler version: GCC 5.5
- Build settings: `<toolset>gcc:<cxxflags>"-std=c++11"`
------
```
toolbox/test/channel_view.cpp: In member function ‘void toolbox_tests::channel_view_test::test_method()’:
toolbox/test/channel_view.cpp:26:12: warning: variable ‘red’ set but not used [-Wunused-but-set-variable]
view_t red = kth_channel_view<0>( const_view( img ));
^
toolbox/test/channel_view.cpp:29:20: warning: variable ‘red_’ set but not used [-Wunused-but-set-variable]
channel_view_t red_ = channel_view< red_t >( const_view( img ));
^
```
```
toolbox/test/indexed_image_test.cpp: In …
```

Fix GCC -Wunused-but-set-variable warning in toolbox tests

---

include/boost/gil/bit_aligned_pixel_reference.hpp
include/boost/gil/color_base_algorithm.hpp
include/boost/gil/concepts/basic.hpp
include/boost/gil/extension/toolbox/color_spaces/ycbcr.hpp
io/test/make.cpp
test/image.cpp
test/pixel.cpp
test/pixel_iterator.cpp
toolbox/test/channel_type.cpp
toolbox/test/channel_view.cpp

Those are places boost::is_same can be replaced in non-intrusive way.
Remaining are types derived from `boost::is_same`, where the replacing
would affect all their uses - effectively switching from `boost::true_/false_` types
to `std::true_type` and `std::false_type`.
Such change needs to come along with Boost.MPL to MP11 migration.

Replace some uses of boost::is_same with std::is_same

---

include/boost/gil/io/path_spec.hpp
io/test/all_formats_test.cpp
io/test/bmp_test.cpp
io/test/jpeg_test.cpp
io/test/make.cpp
io/test/paths.hpp
io/test/png_file_format_test.cpp
io/test/png_read_test.cpp
io/test/png_write_test.cpp
io/test/raw_test.cpp
io/test/targa_test.cpp
io/test/tiff_test.cpp

Remove unused `#include`-s and leave `io/test/paths.hpp` as sole
place of `#include <boost/filesystem.hpp>` for IO tests.
Silence annoying `-Wconversion` or `-Wshorten-64-to-32` warning
from Boost.SmartPtr via Boost.Filesystem:
```
conversion to 'std::atomic<int>::__integral_type {aka int}'
from 'long int' may alter its value
```
------
This should disable numerous instances of the warning below thrown during compilation of IO tests
```
In file included from ../../boost/smart_ptr/detail/atomic_count.hpp:77:0,
from ../../boost/smart_ptr/intrusive_ref_counter.hpp:19,
from ../../boost/filesystem/operations.hpp:32,
from ../../boost/filesystem/convenience.hpp:22,
from io/test/bmp_test.cpp:14:
../../boost/smart_ptr/detail/atomic_count_std_atomic.hpp: In constructor …
```

Tidy up uses of Boost.Filesystem in IO

---

.azure-pipelines.yml
.ci/azure-pipelines/steps-cmake-build-and-test.yml
.ci/azure-pipelines/steps-install-gcc.yml

We need build jobs compiling GIL in C++14 mode to start verifying #231 and similar enhancements specific to C++ version.
Tidy up build jobs naming to include C++ version.
-----
Requested by @sdebionne in https://github.com/boostorg/gil/pull/227#issuecomment-460552577 while prototyping the variant improvements finally submitted in #231

Add C++14 builds using GCC 8 and VS2017 to Azure Pipelines

---

CMakeLists.txt
Jamfile
include/boost/gil/color_base_algorithm.hpp
include/boost/gil/concepts/basic.hpp
include/boost/gil/concepts/channel.hpp
include/boost/gil/concepts/color.hpp
include/boost/gil/concepts/color_base.hpp
include/boost/gil/concepts/concept_check.hpp
include/boost/gil/concepts/image.hpp
include/boost/gil/concepts/image_view.hpp
include/boost/gil/concepts/pixel.hpp
include/boost/gil/concepts/pixel_based.hpp
include/boost/gil/concepts/pixel_dereference.hpp
include/boost/gil/concepts/pixel_iterator.hpp
include/boost/gil/concepts/pixel_locator.hpp
include/boost/gil/concepts/point.hpp
include/boost/gil/io/path_spec.hpp
io/test/paths.hpp
test/CMakeLists.txt
test/Jamfile
test/algorithm/std_fill.cpp
test/gil_test_common.hpp

when building tests with both, Boost.Build and CMake.
Disable concepts check for tests where range (e.g. `std::array`)
used as image pixel - not fully specialised as acceptable pixel type.
Tests of extensions will require more work (e.g. numeric test does not compile).
Closes #228

Build core tests with BOOST_GIL_USE_CONCEPT_CHECK defined

---

include/boost/gil/concepts/dynamic_step.hpp
include/boost/gil/concepts/pixel_iterator.hpp
include/boost/gil/dynamic_step.hpp
include/boost/gil/extension/dynamic_image/any_image_view.hpp
include/boost/gil/extension/dynamic_image/image_view_factory.hpp
include/boost/gil/extension/toolbox/image_types/subchroma_image.hpp
include/boost/gil/image_view.hpp
include/boost/gil/image_view_factory.hpp
include/boost/gil/locator.hpp
include/boost/gil/metafunctions.hpp
include/boost/gil/pixel_iterator.hpp
include/boost/gil/step_iterator.hpp
include/boost/gil/virtual_locator.hpp

Replace all scattered around forward declarations of
`dynamic_{x,y,xy}_step_type` with this common header,
where the templates are also documented.
Refine documentation of `transposed_type` - this is kept
in `locator.hpp` as it is not just related to the dynamic step.

Add dynamic_step.hpp for base templates declaration

---

include/boost/gil.hpp

AFAIU, intention of `gil.hpp` is to include all headers.

Include all public headers in gil.hpp

---

Jamfile

This should help to avoid failures on Travis CI (and possibly others):
>  The job exceeded the maximum log length, and has been terminated.
-----
@stefanseefeld Having more and more tests, I'm afraid, we have no other choice. I also think it's more practical to observe and resolve those extra warnings locally, than based on CI logs. Let's stick to CI providing us with boolean green/red status

Disable detailed warnings on CI builds

---

test/image_view/CMakeLists.txt
test/image_view/Jamfile
test/image_view/dynamic_step.cpp
test/iterator/CMakeLists.txt
test/iterator/Jamfile
test/iterator/dynamic_step.cpp
test/locator/CMakeLists.txt
test/locator/Jamfile
test/locator/dynamic_step.cpp

Basic verification expected specializations of `dynamic_x_step_type`
and `dynamic_y_step_type` are in place.

Add tests for dynamic_{x,y}_step_type specializations

---

.azure-pipelines.yml
.ci/azure-pipelines/steps-install-conan.yml

Attempt to solve recent build failures on Azure Pipelines as reported here, then pip update suggested as a solution:
https://developercommunity.visualstudio.com/content/problem/469073/azp-script-is-installed-in-chostedtoolcachewindows.html
Workaround for the problem was suggested in follow-up to the linked report. Adding this task to Windows jobs in `.azure-pipelines.yml` seems to solve the problem:
```
- task: UsePythonVersion@0
displayName: 'Setup Python'
inputs:
versionSpec: '3.6' 
addToPath: true
architecture: 'x64'
```

[azp] Update Python pip

---

test/CMakeLists.txt
test/color/CMakeLists.txt
test/color/Jamfile
test/color/color_spaces_are_compatible.cpp
test/color/concepts.cpp
test/iterator/CMakeLists.txt
test/iterator/Jamfile
test/iterator/is_planar.cpp
test/pixel/Jamfile
test/pixel/is_pixel.cpp
test/pixel/is_planar.cpp
test/pixel/num_channels.cpp
test/pixel/pixels_are_compatible.cpp

This adds some more compile-time tests for individual metafunctions.
-----
Note, pure compile-time testing performed by Boost.Build only, while CMake runs the tests.

Add test for some channel, color and pixel metafunctions

---

test/algorithm/CMakeLists.txt
test/channel/CMakeLists.txt
test/color/CMakeLists.txt
test/image/CMakeLists.txt
test/image_view/CMakeLists.txt
test/iterator/CMakeLists.txt
test/locator/CMakeLists.txt
test/pixel/CMakeLists.txt
test/pixel/Jamfile
test/pixel/concepts.cpp
test/pixel/is_pixel.cpp
test/pixel/pixel_reference_is_mutable.cpp
test/pixel/test_fixture.cpp
test/pixel/test_fixture.hpp
test/point/CMakeLists.txt

Add test for pixel_reference_is_mutable metafunction.
From the legacy tests
- port value_core and reference_core fixtures, see
https://lists.boost.org/boost-gil/2019/02/0138.php
- port representative pixel types and verify with tests of some
metafunctions.
See clarification of the `core` suffix in the class names: https://lists.boost.org/boost-gil/2019/02/0138.php

Add pixel test fixture with all core pixel types

---

include/boost/gil/color_base_algorithm.hpp
include/boost/gil/color_convert.hpp
include/boost/gil/utilities.hpp

Add number of static assertions to test indices used to access
elements of color mapping sequence are in range.
Fixes #249

Fix gray_t and gray_color_t mismatch in default_color_converter_impl

---

test/pixel/concepts.cpp

The current definition using `typename` fails when compiling
with GCC 4.8 and 4.9, because `typename` is allowed since C++17.
* The C++17 code was introduced in #248
* Failing CircleCI builds: https://circleci.com/gh/boostorg/gil/7123 and https://circleci.com/gh/boostorg/gil/7125
```
libs/gil/test/pixel/concepts.cpp:24:39: error: expected 'class' before 'Concept'
template <template<typename> typename Concept>
^
```
* https://en.cppreference.com/w/cpp/language/template_parameters#Template_template_parameter
-----
By the way, we may want to consider using `class` instead of `typename` in general. For example, if we wanted to follow the [C++ Specification Style Guidelines](https://github.com/cplusplus/draft/wiki/Specification-Style-Guidelines):
> template type parameters use class not …

Use class for template template parameter

---

test/pixel/CMakeLists.txt
test/pixel/Jamfile
test/pixel/bit_aligned_pixel_reference.cpp
test/pixel/is_pixel.cpp
test/pixel/packed_pixel.cpp

Test `bit_aligned_pixel_reference` and `packed_pixel` as well as some of related metafunctions generating types of their members and intermediate specializations.
-----
The new tests are part of MPL to MP11 verification. The uses of `boost::mpl` in the new tests will switch to `boost::mp11`.

Add test for some bit-aligned pixel types and metafunctions

---

Jamfile

Not a full list of used features, but it should be enough. Will wash away failures on unsupported compilers from the regression board.

Add tests requirements

---

include/boost/gil/premultiply.hpp

Fix warning: unused parameter `c` [-Wunused-parameter].
Clean up typographic quotation marks.

Comment unused parameter of channel_premultiply call operator [ci skip]

---

.appveyor.yml
.ci/build-and-test.sh
.circleci/config.yml
.travis.yml
Jamfile

The `cxxstd=11,14,17,...` is the recommended way, announced here https://lists.boost.org/Archives/boost/2017/10/239485.php
* #260 (and its discussion)
-----
/cc @Kojoley

Use Boost.Build 'cxxstd' feature instead of '-std' compiler flag

---

.travis.yml

The newer `libstdc++` versions should ensure better C++11 support.
For example, help to avoid issues like this one observed during MPL to MP11 migration work:
```
error: no template named 'is_trivially_default_constructible'; did you mean 'has_trivial_default_constructor'?
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.8/../../../../include/c++/4.8/type_traits:1211:12:
note: 'has_trivial_default_constructor' declared here
struct has_trivial_default_constructor
^
```
I've learned from @pdimov that _"the first really c++11 version is 4.9"_. Apparently, https://en.cppreference.com/w/cpp/compiler_support summary is not quite accurate:
```
Type traits | N1836 | c++11 | gcc 4.3 | clang 3.0
```
because N1836 is actually pre-C++11 with the old `has_*` traits.

[travis] Update libstdcxx for clang build jobs

---

test/pixel/packed_pixel.cpp

Test additional packed_pixel variants for 3-bit gray and 535-bits rgb.

Update test of packed_pixel with run-time checks

---

.ci/azure-pipelines/steps-cmake-build-and-test.yml

Linux and Windows images now come with pre-installed Boost 1.69.
Since it is not possible to remove GIL headers from it, we should
prefer our deployment of Boost.
* #276
* C/C++: Add the latest 4 versions of Boost 1.66.0 - 1.69.0 (Linux, Windows)
Microsoft/azure-pipelines-image-generation#732
* Document available versions of Boost 1.66.0 - 1.69.0 following #732 update
Microsoft/azure-pipelines-image-generation#845

[azp] Avoid pre-installed Boost 1.69

---

.appveyor.yml
README.md

For existing builds, bump C++ version to 14 which [lowest effective version (and default)](https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version?view=vs-2017) supported by compiler from VS2017.
* Since added C++17 builds use Boost `develop` and not older 1.68, if they pass, it means there indeed is MP11 issue in Boost 1.68 (see https://github.com/boostorg/gil/pull/274#issuecomment-482022037).

[appveyor] Add C++17 builds with VS2017

---

.appveyor.yml
.azure-pipelines.yml
.ci/azure-pipelines/steps-cmake-build-and-test.yml
.ci/azure-pipelines/steps-install-boost.yml
.ci/get-boost.sh
.circleci/config.yml
.travis.yml
CMakeLists.txt

Introduce `get-boost.sh` as Boost downloader for all our CI services.
Credits for `get-boost.sh` idea go to @djarek and @boostorg/beast
* Closes #276
* Solves issue explained in https://github.com/boostorg/gil/pull/274#issuecomment-482022037

[CI] Rationalize deployment of Boost dependencies

---

include/boost/gil/packed_pixel.hpp
include/boost/gil/pixel.hpp

>   C++11 / 20.11.2 Header <type_traits> synopsis
>   1 The behavior of a program that adds specializations for any
>   of the class templates defined in this subclause is undefined
>   unless otherwise specified.
The specializations are not used anywhere, so they are safe to remove
without providing a replacement.
Fixes #283

Fix UB due is_trivially_default_constructible specializations

---

doc/design_guide.rst

Document purpose of cached_location_t

---

include/boost/gil/algorithm.hpp
include/boost/gil/detail/type_traits.hpp

Add similar for `std::is_trivially_destructible`.
This should help to restore support for GCC<5 (credit to @pdimov).
* Fixes #282

Add internal version of std::is_trivially_default_constructible

---

include/boost/gil/detail/type_traits.hpp

Part of restoring/improving support for GCC 4.8 and 4.9.
* #282

GCC 4.8/4.9 define std::is_trivially_destructible

---

doc/design_guide.rst

The "Pixel Locator" was missing from the ToC.

Move Pixel Locator out of Pixel Iterator section

---

.circleci/config.yml
README.md
include/boost/gil/color_base_algorithm.hpp
include/boost/gil/concepts/basic.hpp
include/boost/gil/concepts/channel.hpp
include/boost/gil/concepts/color.hpp
include/boost/gil/concepts/color_base.hpp
include/boost/gil/concepts/concept_check.hpp
include/boost/gil/concepts/dynamic_step.hpp
include/boost/gil/concepts/image.hpp
include/boost/gil/concepts/image_view.hpp
include/boost/gil/concepts/pixel.hpp
include/boost/gil/concepts/pixel_based.hpp
include/boost/gil/concepts/pixel_dereference.hpp
include/boost/gil/concepts/pixel_iterator.hpp
include/boost/gil/concepts/pixel_locator.hpp
include/boost/gil/concepts/point.hpp
include/boost/gil/io/path_spec.hpp
io/test/paths.hpp
numeric/test/numeric.cpp
test/channel/concepts.cpp
test/unit_test.hpp
toolbox/test/lab_test.cpp

Although GCC 4.8 is labelled as C++11 compatible, the reasons are:
* GCC 4.8 is buggy enough to prevent reasonable use of Boost.MP11
* GCC 4.8 is dying
* Closes #282

Officially drop support for GCC <= 4.8

---

include/boost/gil/point.hpp
test/point/Jamfile
test/point/multiply_by_non_arithmetic_fail.cpp

Add Boost.Build-only test to verify compilation failure.
Fixes #289 as better solution than #294 workaround.
-----
This follows suggestion from @stefanseefeld in https://github.com/boostorg/gil/pull/294#issuecomment-486805343

Disable free operator* of point<T> for non-arithmetic operand

---

include/boost/gil/detail/std_common_type.hpp
include/boost/gil/point.hpp

It should help to improve uses of SFINAE like the one from #295 and fix #289 for MSVC 14.0 (VS2015) for good.
Copied from Boost.Hana.
Simply, SFINAE using `std::common_type` turned out to be insufficient, at least it was still not working well with VS2015. The issue was revealed by `matrix3x2` tests added in #293 for which VS2015 build jobs failed (e.g. https://ci.appveyor.com/project/mloskot/gil/build/job/c7xrfsikib6la83g).
Since the `std::common_type` is a very useful trait and it may be suitable in future cases where common type needs to be calculated, it is a good idea to have a solid SFINAE-friendly version available.
* Refines #295 which was based on the idea from https://github.com/boostorg/gil/pull/294#issuecomment-486805343
------

Add SFINAE-friendly version of std::common_type

---

.gitignore
example/interleaved_ptr.hpp

Fixed a syntax error in examples, missing = sign.
- Compiler version: VC++  19.16.27030.1
- Build settings: use_conan=true, others default
- GIL Version (Git ref or `<boost/version.hpp>`): https://github.com/boostorg/gil/commit/10f1efff5bbb86bc79341601e341fc9fa86cfdf5
Mentioned in gitter

Add missing equal sign in interleaved_ptr.hpp

---

numeric/test/CMakeLists.txt
numeric/test/Jamfile
numeric/test/matrix3x2.cpp
numeric/test/numeric.cpp

Additionally, in numeric.cpp:
- Add `#include "unit_test.hpp"` - proxy header common to all GIL tests.
- Tidy up copyright notice.

[numeric] Add unit test for matrix3x2<T> class

---

include/boost/gil/extension/io/raw/tags.hpp

Apparently, for some not entirely clear reasons, possibly historical use of `.vcproj`, LibRaw uses (not defines!) `WIN32` macro, instead of C standard compliant `_WIN32` common to majority of compilers on Windows.
This patch is required if GIL IO is used with Boost.Build or custom Makefile, without this custom `WIN32` hand-rolled in build configuration.
Hopefully, LibRaw may accept some clean up for this in near future: https://github.com/LibRaw/LibRaw/pull/206

Define WIN32 macro to make LibRaw happy

---

test/core/color/concepts.cpp
test/core/color_base/concepts.cpp
test/core/image/concepts.cpp
test/core/image_view/concepts.cpp
test/core/iterator/concepts.cpp
test/core/locator/concepts.cpp
test/core/pixel/concepts.cpp
test/core/point/concepts.cpp

Avoid Clang's flooding of non-disableable warnings like:
> T does not declare any constructor to initialize its non-modifiable members
when compiling with concepts check enabled.
Bug 41759: `warn_no_constructor_for_refconst` can not be disabled (Boost.ConceptCheck)
https://bugs.llvm.org/show_bug.cgi?id=41759
- Compiler version: clang

Disable BOOST_GIL_USE_CONCEPT_CHECK when compiling tests with clang

---

.ci/get-boost.sh

This PR fixes the CI logic that assumed the fork was named "gil". (Failures to be observed i.e. 
https://travis-ci.org/BoostGSoC19/gil-olzhas/jobs/540510185).

Fix setup logic to also work with differently named GIL forks.

---

.azure-pipelines.yml
.ci/azure-pipelines/steps-cmake-build-and-test.yml
CMakeLists.txt
CONTRIBUTING.md
example/cmake/CMakeSettings.json

Upcoming [CMake 3.15](https://cmake.org/pipermail/cmake/2019-June/069548.html) introduced more dependencies in FindBoost.cmake what makes the downloading impractical.

[CMake] Remove GIL_DOWNLOAD_FINDBOOST option

---

.ci/get-boost.sh
include/boost/gil/detail/math.hpp
include/boost/gil/image_processing/numeric.hpp
include/boost/gil/image_processing/scaling.hpp
test/core/image_processing/CMakeLists.txt
test/core/image_processing/Jamfile
test/core/image_processing/lanczos_scaling.cpp

This is milestone merge after implementing lanczos scaling
Everything that supports Boost 1.70
https://en.wikipedia.org/wiki/Lanczos_resampling

Implementation of lanczos down scaling

---

test/core/color_base/CMakeLists.txt
test/core/color_base/Jamfile
test/core/color_base/static_transform.cpp
test/core/color_base/static_transform_gray_to_rgb_fail.cpp
test/core/color_base/static_transform_rgb_to_cmyk_fail.cpp

The test also illustrates and verifies that the `static_transform` is constrained by the size of destination color base.
That is, it is applicable if the source color base has number of elements equal-to or greater-than the destination color base.
------
I am not entirely sure if this behaviour is by design or by some sort of accident. For example, it is possible that some compile-time checks are simply missing e.g. refusing the case source of wider to narrower color base and requiring equal size of both color bases.
However, this test verifies (and documents) current behaviour w/o changing it.

Add basic test for color base algorithm: static_transform

---

include/boost/gil/extension/numeric/convolve.hpp
include/boost/gil/extension/numeric/kernel.hpp
test/extension/numeric/Jamfile
test/extension/numeric/kernel.cpp
test/extension/numeric/kernel_1d_fixed_even_size_fail.cpp

Use of `std::extent` was introduced in PR #200 but it turns out as not applicable for `std::array` or derived types (e.g. `kernel_1d_fixed`).
This led to obtaining invalid size of `kernel_1d_fixed` and erroneous results of the rows and columns convolution.
This change replaces `std::extent` with new public constant member `kernel_1d_fixed::static_size`.
Since `kernel_1d_fixed` is derived from `std::array`, the alternative could be to use `std::tuple_size` specialization for `std::array`.
Additionally, add static assertion to require that _kernel size must be odd to ensure validity at the center_.
- #200 and related

[numeric] std::extent not usable to obtain size of kernel_1d_fixed

---

include/boost/gil/image_view.hpp
include/boost/gil/iterator_from_2d.hpp
include/boost/gil/locator.hpp

Add copy assignment operator to `memory_based_2d_locator` and `iterator_from_2d`.
Add copy constructor to `image_view` which already has copy assignment operator.
Fix GCC 9 warning [-Wdeprecated-copy](https://gcc.gnu.org/onlinedocs/gcc-9.1.0/gcc/C_002b_002b-Dialect-Options.html#index-Wdeprecated-copy) that:
> implicit declaration of a copy constructor or copy assignment operator
> is deprecated if the class has a user-provided copy constructor or
> copy assignment operator, in C++11 and up."
- https://en.wikipedia.org/wiki/Rule_of_three_(C%2B%2B_programming)

Apply the rule of three in memory_based_2d_locator and iterator_from_2d

---

include/boost/gil/channel_algorithm.hpp

This PR adds suppressing parentheses to the std::numeric_limits<UnsignedIntegralChannel>::max to avoid windows.h redefinition issues that may arise when boost/gil is used in large projects with other libraries.
- Compiler version: Boost.Build 4.0-git
- Build settings:
- GIL Version (Git ref or `<boost/version.hpp>`): 107100
*Link related issues, pull requests here, mailing list, stackoverflow, etc.*

Add suppressive parentheses for function-like macro

---

include/boost/gil/detail/math.hpp
include/boost/gil/image_processing/numeric.hpp
include/boost/gil/image_processing/scaling.hpp

Add missing `inline` specifier for tiny functions.
Add missing include guards.
Add missing copyright notice.
Remove superfluous `boost::gil::` namespace qualifiers.
Make use of 100 characters line length limit:
- Remove superfluous newlines to avoid too much of vertical stretch.
- Tidy up Doxygen comments.
------
FYI @simmplecoder

Tidy up headers in gil/image_processing/ directory

---

include/boost/gil.hpp

Header missing from the all-in-one `gil.hpp`

[gsoc2019] Add image_processing/scaling.hpp to boost/gil.hpp

---

include/boost/gil/image_processing/threshold.hpp
test/core/image_processing/Jamfile
test/core/image_processing/threshold_color_spaces_not_compatible_fail.cpp

Since use of `gil_function_requires` check is optional, it can be disabled by not defining `BOOST_GIL_USE_CONCEPT_CHECK`, we need a mandatory form of the check.
Closes #323
------
/cc @miralshah365

[gsoc2019] Add color_spaces_are_compatible requirement as static_assert to threshold

---

include/boost/gil/image_processing/threshold.hpp

*Changed comparison operator in all the lambda function in `threshold.hpp` from `>=` to `>`.*
1. To provide uniform behavior with other image processing libraries.
2. Thresholds are boundary and boundaries are not included in the threshold values.
3. See https://github.com/boostorg/gil/pull/321#issuecomment-508844056

Comparison operator changed to `>` from `>=` for threshold

---

include/boost/gil/concepts/pixel_locator.hpp
include/boost/gil/rgba.hpp
test/core/image_view/CMakeLists.txt
test/core/image_view/Jamfile
test/core/image_view/planar_rgba_view.cpp

Add basic run-time test of `planar_rgba_view` function.
Add missing include of `planar_pixel_reference.hpp` also required
for successful compilation.
- Fixes #331

Fix error: RView identifier not found in planar_rgba_view

---

doc/doxyfile
doc/reference.dox

Enable API reference geneartion for the GSoC 2019 features.
-----
@simmplecoder & @miralshah365 FYI, this should fix the problem you were reporting on Gitter about docs for your code.
The critical part is `\defgroup ImageProcessing` added in https://github.com/boostorg/gil/compare/develop...mloskot:ml/doc-add-image-processing?expand=1#diff-99612ff6bcbef4bb2ccde36f09ea3884R192
Then, enable grouping with `ImageProcessing` for your headers, http://www.doxygen.nl/manual/grouping.html, using `\ingroup` or `\addtogroup`.

Add Image Processing section to Doxygen-based docs

---

test/core/pixel/test_fixture.hpp
test/extension/numeric/CMakeLists.txt
test/extension/numeric/Jamfile
test/extension/numeric/convolve_2d.cpp
test/extension/numeric/convolve_cols.cpp
test/extension/numeric/convolve_rows.cpp
test/extension/numeric/test_fixture.cpp
test/extension/numeric/test_fixture.hpp
test/unit_test.hpp

First stab at convolution tests includes cases with the identity kernel.
Move `pixel`-s streaming facility used by Boost.Test (required  by `BOOST_TEST` macro) to the common header for re-use in other tests.
------
/cc @miralshah365

Add first tests for convolve functions from Numeric extension

---

include/boost/gil/image_processing/numeric.hpp

Fixes `-Wfloat-equal` warning.

Compare float-pointing value to zero using <= operator

---

test/core/image_view/subimage_view.cpp
test/core/pixel/test_fixture.cpp
test/extension/dynamic_image/subimage_view.cpp
test/extension/numeric/convolve_2d.cpp
test/extension/numeric/convolve_cols.cpp
test/extension/numeric/convolve_rows.cpp
test/unit_test.hpp
test/unit_test_utility.hpp

_Refactoring only, no functional changes._
Add separate header `test/unit_test_utility.hpp` for printers and
other utilities for better integration of GIL types with Boost.Test.

Extract GIL-specific Boost.Test utilities from test/unit_test.hpp

---

include/boost/gil/image_processing/threshold.hpp
test/core/image_processing/CMakeLists.txt
test/core/image_processing/Jamfile
test/core/image_processing/threshold_otsu.cpp

New method threshold_optimal introduced. In this method, the user does not need to specify any threshold value but is chosen by the Otsu's algorithm. More details about the algorithm can be found in the reference.
If the image is multi-channel then the algorithm is applied on each channel. If the image has channel depth more than 8bit then each channel is normalized to fit in the range from 0 to 255.
closes #311
http://www.labbookpages.co.uk/software/imgProc/otsuThreshold.html

[gsoc2019] Otsu threshold implemented

---

include/boost/gil/extension/numeric/convolve.hpp

This function combines both `convolve_rows` and `convolve_cols` into a single call for user convenience.
The need for such function came into the sight when @miralshah365 was implementing `adaptive_threshold` and encountered error due to multiple calls to convolve function with the same source instead of using the result of the first convolution as the source for other.

`convolve` function added

---

include/boost/gil/image.hpp
include/boost/gil/image_view.hpp

These assertions validating user-specified x and y values for pixel positions at run-time should help GIL users to catch basic mistakes as early as possible, especially during complex processing algorithms.
(Easy to make a mistake calling `view(y, x)` instead of `view(x, y)`!)
The checks are deliberately implemented using assertions as debug-only tools disabled in `NDEBUG` builds, and not as exceptions to avoid potentially significant performance hit at run-time in optimised builds.
Add `TODO` comments where certain assumptions are not immediately obvious and may require further testing to clarify and documenting. For example, what are constraints on requesting locators with negative offsets using `image_view::xy_at`?
Tidy up image.hpp and image_view.hpp formatting vertically rather than …

Assert user-specified positions within image or image_view are in range

---

include/boost/gil/image_processing/numeric.hpp
test/core/image_processing/CMakeLists.txt
test/core/image_processing/Jamfile
test/core/image_processing/simple_kernels.cpp

Add generators for box (normalized and unnormalized) kernel and Gaussian kernel.
Anything compatible with Boost 1.70
https://en.wikipedia.org/wiki/Gaussian_blur
https://en.wikipedia.org/wiki/Box_blur

Filter generation

---

example/adaptive_threshold.cpp
example/convolution.cpp
example/interleaved_ptr.cpp
example/interleaved_ptr.hpp
example/interleaved_ref.hpp

A typical user is supposed to include the main header and to not know the library enough to include headers selectively.

Include <boost/gil.hpp> in examples

---

include/boost/gil/extension/numeric/kernel.hpp
test/extension/numeric/kernel.cpp

for more detail check the reference(s)
#356

Added 2D kernel definitions to numeric extension

---

example/convolve2d.cpp
include/boost/gil/extension/numeric/convolve.hpp
include/boost/gil/image_processing/threshold.hpp
test/extension/numeric/CMakeLists.txt
test/extension/numeric/Jamfile
test/extension/numeric/convolve.cpp
test/extension/numeric/convolve_2d.cpp

`convolve` function renamed to `convolve_1d`
for more detail check the reference(s)
closes #356

Added 2D convolution definitions to numeric extension

---

test/extension/io/Jamfile

This addresses issues during the Boost regression runs, where builders only provide popular third-party libraries (i.e. libraw is missing).
- @mjcaisse pointed out the problem https://cpplang.slack.com/archives/C27KZLB0X/p1565130435280100

Mark all non-simple build targets of extension/io as explicit

---

example/Jamfile
example/harris.cpp
include/boost/gil/image_processing/harris.hpp
include/boost/gil/image_processing/numeric.hpp
test/core/image_processing/CMakeLists.txt
test/core/image_processing/Jamfile
test/core/image_processing/harris.cpp

Implement Harris corner detection, but without suggested result filtering. The algorithm writes Harris responses into `gray32_view_t` and the user can apply their chosen filtering/suppression algorithms. Loosening filtering will give edge detector.
Everything compatible with Boost 1.70
https://en.wikipedia.org/wiki/Harris_Corner_Detector
https://en.wikipedia.org/wiki/Structure_tensor
https://en.wikipedia.org/wiki/Image_derivatives
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.434.4816&rep=rep1&type=pdf

Harris response computation

---

example/hessian.cpp
include/boost/gil/image_processing/hessian.hpp
include/boost/gil/image_processing/numeric.hpp
test/core/image_processing/CMakeLists.txt
test/core/image_processing/Jamfile
test/core/image_processing/hessian.cpp

This commit implements Hessian corner detector, with response function being the same as in [Harris](https://github.com/boostorg/gil/pull/350). 
Anything compatible with Boost 1.70
https://en.wikipedia.org/wiki/Hessian_matrix

Hessian corner detector

---

include/boost/gil/image_processing/filter.hpp
test/core/image_processing/CMakeLists.txt
test/core/image_processing/Jamfile
test/core/image_processing/box_filter.cpp

implemented `blur` function
tests added for `box_filter`
This utility will provide a way to remove noise from the image using convolution with `average` kernel(normalized and unnormalized).
It also provides `blur` function which works only with normalized mean kernels
closes #382

Add implementatin of box filter and blur

---

include/boost/gil/extension/io/png/detail/base.hpp

**Use of `BOOST_ASSERT` in `png_ptr_read_deleter` and `png_ptr_write_deleter` in ‎⁨`include/boost/gil/extension/⁨io/png/⁨detail⁩/reader_backend.hpp` will produce a crash with PNG files with an invalid header.**
In such a case (bad PNG file), we expect a `std::ios_base::failure` exception (see below).  
Unfortunately, the assertions will prevent the exception to be caught by terminating the program.
This hotfix replaces the assertions with conditional checks, so we can get the expected exception handling.
1. Create a text file with at least 4 characters (like `ABCD`).
2. Try to read the file as PNG:
using backend_t   = typename boost::gil::get_reader_backend< std::string, boost::gil::png_tag >::type;
backend_t backend = boost::gil::read_image_info( "path/to/invalid/png", …

Fixed a crash when reading PNG files with an invalid header.

---

include/boost/gil/extension/numeric/algorithm.hpp
test/extension/numeric/CMakeLists.txt
test/extension/numeric/extend_boundary.cpp

A new algorithm for image boundary extension added.
This can help with simplifying algorithms like convolution and median filter which is being implemented by @miralshah365.
While extending current `convolve_2d` this will allow all type of convolve options to be accommodated easily and current `convolve_1d` and also use to this to provide a uniform implementation.
#381

Image boundary extension algorithm added

---

include/boost/gil/image_processing/filter.hpp
test/core/image_processing/CMakeLists.txt
test/core/image_processing/Jamfile
test/core/image_processing/median_filter.cpp

implemented `median_filter` function
tests added for `median_filter`
This utility will provide a way to remove noise from the image by choosing a median value from a window which iterates over entire image.

Implemented median_filter

---

example/convolve2d.cpp
include/boost/gil/extension/numeric/convolve.hpp
include/boost/gil/extension/numeric/kernel.hpp
include/boost/gil/image_processing/filter.hpp
include/boost/gil/image_processing/threshold.hpp
test/extension/numeric/convolve.cpp
test/extension/numeric/convolve_2d.cpp
test/extension/numeric/kernel.cpp

Following @lpranam comments on planned changes to `convolve_2d`, which will not be ready for Boost 1.72, @mloskot proposed to hide the function as implementation detail, https://lists.boost.org/boost-gil/2019/10/0316.php, until it is ready and @stefanseefeld agreed on the proposal, https://lists.boost.org/boost-gil/2019/10/0320.php.
- PR #347
- PR #367
- Issue #381 with planned changes by @lpranam too, https://lists.boost.org/boost-gil/2019/10/0315.php

Hide convolve_1d, convolve_2d and kernel_2 in namespace detail

---

include/boost/gil/extension/numeric/algorithm.hpp
test/extension/numeric/extend_boundary.cpp

Added new case where `extend_padded` boundary option will assume source view to be already padded and will return the original image. 
Other boundary options `output_ignore` and `output_zero` will not be allowed in this function as they do not make any sense with boundary extension but to be used with convolution operations.
closes #391

Update extend_boundary function to handle all boundary_option-s

---

RELEASES.md

This proposes to use Git to maintain notes about all notable changes to GIL in `RELEASES.md` file based on https://keepachangelog.com format.
Collect all past release notes.
Collect release notes for the pending Boost 1.72.0, in section [Unreleased].
> **IMPORTANT:** Before Boost release is issued, our release notes from `RELEASES.md` should be copied and added to relevant file in https://github.com/boostorg/website/tree/master/feed/history
This implements proposal discussed and agreed in the thread https://lists.boost.org/boost-gil/2019/11/0336.php
------
It is possible to integrate the release notes into Sphinx-generated documentation. It will be implemented as soon as this proposal is merged.

Add release notes in Markdown format

---

.editorconfig
RELEASES.md

The log of significant changes prior the first release of GIL as part of Boost was collected from https://stlab.adobe.com/gil/news.html site  and from the linked PDF documents with detailed descriptions.
The old history is very detailed (after the PDFs) but it is interesting.
It illustrates evolution of the library design and API, for example, renaming of types or functions were renamed indicates evolution of semantics and inter-relations of the library elements.
This is especially interesting in case of the complex types like bit-aligned pixels and images, where does the concept of memunit come from, etc.
- Updates #404

Import pre-Boost history of GIL by Adobe to release notes

---

include/boost/gil/concepts/concept_check.hpp
include/boost/gil/extension/dynamic_image/dynamic_at_c.hpp
include/boost/gil/extension/dynamic_image/reduce.hpp
include/boost/gil/extension/toolbox/color_spaces/cmyka.hpp
include/boost/gil/extension/toolbox/color_spaces/gray_alpha.hpp
include/boost/gil/extension/toolbox/color_spaces/hsl.hpp
include/boost/gil/extension/toolbox/color_spaces/hsv.hpp
include/boost/gil/extension/toolbox/color_spaces/lab.hpp
include/boost/gil/extension/toolbox/color_spaces/xyz.hpp
include/boost/gil/extension/toolbox/color_spaces/ycbcr.hpp
include/boost/gil/image_view_factory.hpp
include/boost/gil/iterator_from_2d.hpp
include/boost/gil/locator.hpp
include/boost/gil/pixel_iterator_adaptor.hpp
include/boost/gil/step_iterator.hpp
include/boost/gil/typedefs.hpp
test/core/channel/algorithm_channel_convert.cpp
test/legacy/performance.cpp
test/legacy/recreate_image.cpp

Prefixes some macros with _BOOST_
This pull request closes https://github.com/boostorg/gil/issues/410

Prefixed macros with BOOST

---

include/boost/gil/extension/io/png/detail/read.hpp
test/extension/io/png_read_test.cpp

This pull request fixes https://github.com/boostorg/gil/issues/401#issue-518615480 by replicating the mechanism used in jpeg reader. Since on initialization the error handling mechanism is not selected, libpng uses default one, which is through setjmp/longjmp (the same as in jpeg). There is also a test that confirms the case is covered.
https://github.com/boostorg/gil/issues/401#issue-518615480

Fix #401: segmentation fault when reading purposely corrupted png image

---

CONTRIBUTING.md

There is a need to run 
```shell
./b2 -j8 headers
```
otherwise, some other directory iterators do not create.

Make b2 headers non-optional to simplify instructions

---

include/boost/gil/image.hpp
test/core/image/CMakeLists.txt
test/core/image/Jamfile
test/core/image/image.cpp

Fixes missing default value for `alignment` argument of one of the `image` constructor overloads.
Fixes #424 blocking PR #423

Fix missing alignment default value in image constructor

---

include/boost/gil/extension/io/jpeg/detail/write.hpp
include/boost/gil/extension/io/jpeg/detail/writer_backend.hpp

This pull request removes the `jpeg_finish_compress` call from destructor, which will ensure no erroring function can be called when an exception is in flight or the destructor can fail. If we would throw out of destructor some time in the future, we will have to put `noexcept(false)`, as destructors are `noexcept` by default.
Thanks a lot to [@misos1](https://github.com/misos1) for having productive discussion about the `setjmp` and `longjmp` in the [original issue](https://github.com/boostorg/gil/issues/416).
#416

Move jpeg_finish_compress out of destructor

---

doc/design/concepts.rst

Fixed typo in Boost.Gil's design guide [concepts](https://boostorg.github.io/gil/html/design/concepts.html) page as mentioned in the comments of #272 .

Fixed typo(T y->U y) in concepts.rst

---

include/boost/gil/promote_integral.hpp

This PR is to replace all occurrences of **Boost.mpl's** meta functions with equivalents from **Boost.mp11** as mentioned in #280. I have tried to make **minimal** number of changes to the source code while using only functionality from Boost.mp11 . I have also tried using other ways to do the replacement using mp_find_if or mp_cond from the mp11 docs but this PR proposes using mp_rest to recurse over the type list.
https://www.boost.org/doc/libs/develop/libs/mp11/doc/html/mp11.html#mp_restl
https://www.boost.org/doc/libs/develop/libs/mp11/doc/html/mp11.html#mp_find_ifl_p
https://www.boost.org/doc/libs/develop/libs/mp11/doc/html/mp11.html#mp_condc_t_r

Replace Boost.MPL with Boost.MP11 in promote_integral.hpp

---

include/boost/gil/image_view.hpp
test/core/image_view/CMakeLists.txt
test/core/image_view/Jamfile
test/core/image_view/iteration.cpp

The commit changes assert condition
to temporary fix the problem. There are
also very basic tests that will check
for regression.
Fix for #432 
#432

Fix incorrect assert caught in image_view::col_end 

---

.travis.yml

This just fixes CI infrastructure issue, APT conflict.
We no longer need to allow `VARIANT=gil_ubsan_integer` job to fail.

Remove llvm-toolchain-trusty-6.0 from APT sources as unused

---

CMakeLists.txt
test/Jamfile

Remove setting flags specific to `CMAKE_CXX_CLANG_TIDY` as likely not necessary
- restore if it causes issues.
If `CI` (Travis CI, AppVeyor, CircleCI) or `AGENT_JOBSTATUS` (Azure Pipelines) or `GITHUB_ACTIONS` (GitHub Actions) environment variable is defined, then do not set high compiler warning levels.

CI: Avoid huge logs due to compilation warnings

---

.appveyor.yml
test/legacy/image.cpp

It is **not a fix** but workaround based on #447 applied in order to  avoid continuous failures of the checksum tests run by CI jobs.
Make related AppVeyor builds with MSVC++ no longer allowed to fail.
- #447

Fix legacy test with workaround for MSVC++ 64-bit optimized build

---

doc/design/dynamic_image.rst
include/boost/gil/extension/dynamic_image/any_image_view.hpp
test/extension/dynamic_image/subimage_view.cpp

Adds `any_image_view::size()` that returns the size of the underlying `image_view`.
```
size_type        View::size()       const; // total number of elements
```

Add any_image_view::size()

---

test/extension/io/Jamfile
test/extension/io/paths.hpp
test/extension/io/simple_all_formats.cpp

This is part of efforts removing use of compile-time configuration macros
- `BOOST_GIL_IO_TEST_ALLOW_READING_IMAGES`
- `BOOST_GIL_IO_TEST_ALLOW_WRITING_IMAGES`
The idea of getting rid of the macros was introduce here https://lists.boost.org/boost-gil//2019/07/0279.php

Always build test/extension/io//simple if format libraries are available

---

include/boost/gil/detail/math.hpp
include/boost/gil/image_processing/numeric.hpp
test/core/image_processing/sobel_scharr.cpp

Addresses #471. The constants are not part of public interface.
#471

Move math.hpp constants to detail namespace

---

include/boost/gil/image.hpp
test/core/image/image.cpp

Add move semantic to `image`.
- Fix part of #438
- [[gil] Review of move assignment operator for image class](https://lists.boost.org/Archives/boost/2020/03/248582.php)

Add move semantics to image class

---

include/boost/gil/color_convert.hpp
test/core/pixel/CMakeLists.txt
test/core/pixel/Jamfile
test/core/pixel/color_convert_cmyk.cpp

Correct calculation to correctly map CMYK 0 to minimum and 1 to maximum of input and output channel types.
If float-point division is necessary, use double instead of float which may be too narrow for large operands. `cmyk32_pixel_t` is based on `uint32_t` which multiplication by its maximum may yield result too large to fit 32-bit float.
For example, `(uint32_t(c) -  uint32_t(k)) * float(s)` for`c = 4294967295, k = 0, s = 1.0`
results in `4294967300` value which does not fit `uint32_t`.
**FIXME:** The original calculation was broken for signed CMYK target types. This has not been corrected yet.
- Fixes #406
- https://web.archive.org/web/20061119141350/www.neuro.sfc.keio.ac.jp/~aly/polygon/info/color-space-faq.html

Fix invalid conversion from RGB8 to CMYK32 due to overflow

---

include/boost/gil/image.hpp
test/core/image/image.cpp
test/core/image/test_fixture.hpp

Fixes
```c++
template <typename P2, bool IP2, typename Alloc2>
image(const image<P2,IP2,Alloc2>& img)
```
giving
```
include/boost/gil/image.hpp:108:84: error: 'std::size_t boost::gil::image<boost::gil::pixel<unsigned char, boost::gil
::layout<boost::mp11::mp_list<boost::gil::gray_color_t> > >, false, std::allocator<unsigned char> >::_align_in_bytes' is
private within this context
image(const image<P2,IP2,Alloc2>& img) : _memory(nullptr), _align_in_bytes(img._align_in_bytes), _alloc(img._alloc)
~~~~^~~~~~~~~~~~~~~
../include/boost/gil/image.hpp:345:20: note: declared private here
std::size_t    _align_in_bytes;
```
- Raised on [Slack](https://cpplang.slack.com/archives/CSVT0STV2/p1586328948062100).
- Work on this revealed #478 issue

Fix image constructor from other image

---

include/boost/gil/extension/toolbox/image_types/subchroma_image.hpp

Issued when compiling toolbox extension using MSVC 14.x with `-permissive-` flag for strict mode.
Fixes #480

Fix error plane_view_t is not a class or namespace name

---

.appveyor.yml
.ci/get-boost.sh
.travis.yml
doc/design/dynamic_image.rst
example/dynamic_image.cpp
include/boost/gil/extension/dynamic_image/algorithm.hpp
include/boost/gil/extension/dynamic_image/any_image.hpp
include/boost/gil/extension/dynamic_image/any_image_view.hpp
include/boost/gil/extension/dynamic_image/apply_operation.hpp
include/boost/gil/extension/dynamic_image/image_view_factory.hpp
include/boost/gil/extension/io/bmp/detail/read.hpp
include/boost/gil/extension/io/bmp/detail/write.hpp
include/boost/gil/extension/io/jpeg/detail/read.hpp
include/boost/gil/extension/io/jpeg/detail/write.hpp
include/boost/gil/extension/io/png/detail/read.hpp
include/boost/gil/extension/io/png/detail/write.hpp
include/boost/gil/extension/io/pnm/detail/read.hpp
include/boost/gil/extension/io/pnm/detail/write.hpp
include/boost/gil/extension/io/raw/detail/read.hpp
include/boost/gil/extension/io/targa/detail/read.hpp
include/boost/gil/extension/io/targa/detail/write.hpp
include/boost/gil/extension/io/tiff/detail/read.hpp
include/boost/gil/extension/io/tiff/detail/write.hpp
include/boost/gil/extension/numeric/resample.hpp
include/boost/gil/extension/toolbox/metafunctions/get_pixel_type.hpp
include/boost/gil/io/dynamic_io_new.hpp
include/boost/gil/io/read_image.hpp
include/boost/gil/io/write_view.hpp
test/extension/dynamic_image/test_fixture.hpp
test/legacy/image.cpp

Implements dynamic extension with Boost.Variant2 instead of Boost.Variant.
Fixes #232

Replace Boost.Variant with Boost.Variant2

---

include/boost/gil/image_view_factory.hpp

Stick to the existing convention of `ptrdiff_t` and ensure it is used consistently across the existing code and new code.
https://cpplang.slack.com/archives/CSVT0STV2/p1587562275123700

Fix interleaved_view factory using point<std::ptrdiff_t> for dimension

---

include/boost/gil/extension/dynamic_image/any_image.hpp
test/extension/dynamic_image/CMakeLists.txt
test/extension/dynamic_image/Jamfile
test/extension/dynamic_image/any_image.cpp

Add a new constructor to `any_image`.
Fixed #453

Add initializing image constructor

---

include/boost/gil/extension/numeric/algorithm.hpp

Added missing `const&` to all the extend_boudary related functions

added missing const& in extend_boundary parameters

---

include/boost/gil/extension/numeric/kernel.hpp
test/extension/numeric/kernel.cpp

Provided overloads to reverse `kernel_2d` and `kernel_2d_fixed`

Implemented mechanism to reverse kernel_2d

---

include/boost/gil/extension/dynamic_image/apply_operation.hpp

Add a couple of overloads of `apply_operation` for binary operations. This is necessary until boostorg/variant2#20 is implemented. At that point `apply_operation` won't be necessary anymore (or could perfect forward to `visit`).

Use perfect forwarding from apply_operation to visit

---

include/boost/gil/extension/dynamic_image/dynamic_image_all.hpp
test/extension/toolbox/channel_type.cpp

Remove `#include <boost/gil.hpp>` from `<boost/gil/extension/dynamic_image/dynamic_image_all.hpp>`. It ends up that all individual headers in the extension were already including what they need.
Fixes #501

Fix dynamic_image extension header dependencies

---

test/CMakeLists.txt

I am not sure why they were disabledin the first place...

Re-enable self containing header tests in CMake

---

include/boost/gil/extension/dynamic_image/apply_operation.hpp

Fix a regression introduce in #491 when building with -std=c++11
Fixes #510

Fix dynamic image apply_operation when building with -std=c++11

---

include/boost/gil/color_convert.hpp
test/core/color/CMakeLists.txt
test/core/color/Jamfile
test/core/color/default_color_converter_rgb_to_cmyk.cpp

Conversion of RGB pixels based on unsigned integral channels to CMYK based on signed integral channels was/is broken (issue #479). It happend because relations used for color correction like `c' = (c - k) * s` etc. didn't work well for signed integral channels. 
This correction is attempted by doing **all color correction calculations of pixel values based on unsigned** integral channels then(after the calculations are finished) converting those values to signed ones.
Principles of Digital Image Processing - Fundamental Techniques (Book name provided in `color_convert.hpp`)

Fix conversion of rgb to signed cmyk(boostorg#479)

---

.gitignore
include/boost/gil/image.hpp
test/core/image/image.cpp

For convenience, this PR introduces a new image constructor to "materialize" (in the SQL sense) an image_view.

Add image constructor from compatible view

---

include/boost/gil/extension/toolbox/color_spaces/hsv.hpp

Removes an unnecessary numeric_cast in include\boost\gil\extension\toolbox\color_spaces\hsv.hpp that casts from float32_t to float32_t.
This removes the only dependency on Boost.NumericConversion I could find
https://cpplang.slack.com/archives/C27KZLB0X/p1605793604490300

Remove unnecessary numeric_cast in hsv.hpp

---

.ci/coverage.sh
.travis.yml

This PR adds code coverage using [Codecov](https://about.codecov.io/) as mentioned in #420 . Currently being generated using the Travis CI pipeline.
* https://docs.codecov.io/docs
* https://docs.codecov.io/docs
* https://github.com/boostorg/beast

Add codecov coverage

---

include/boost/gil/extension/numeric/affine.hpp
test/extension/numeric/matrix3x2.cpp

Adds `inverse(boost::gil::matrix3x2<T> m)` that returns the inverse of the given affine matrix to the `numeric` extension. This is useful to implement an undo of an affine transformation or to compute the coordinate of points in the original coordinate system gievn the coordinate in transformed one. 
Use `BOOST_TEST_WITH` and defines `with_tolerance` rather `BOOST_GIL_TEST_IS_CLOSE` as discussed in boostorg/core#38

Add inverse function for affine matrix3x2

---

test/extension/toolbox/Jamfile

I discovered another typo in copyright headers. Sorry for not noticing this in my first PR.

Fix typo in copyright headers.

---

include/boost/gil/color_base.hpp
test/core/pixel/test_fixture.hpp

If `Element` is a reference, then Element v{} is ill-formed.
- Refines #273 which aimed to correctly value-initialize channel and pixel value members

Fix default ctor of homogeneous_color_base for reference pixel elements

---

example/harris.cpp
example/hvstack.hpp

Adds ability to stack images either horizontally or vertically. Provides output view argument form and image returning form for convenience. Does full input checking. This is rough version only, not intended for usage outside writing examples.
https://cpplang.slack.com/archives/CSVT0STV2/p1594414134118400

Implement hstack and vstack

---

.github/workflows/ci.yml
test/core/channel/algorithm_channel_relation.cpp

R.I.P. Travis CI. Long live GitHub Actions.
This configuration has been copied from [boostorg/mp11](https://github.com/boostorg/mp11/blob/2d709e5639e92c5ba84d99bad740bfeb06fd6a4f/.github/workflows/ci.yml).
Removal of our `.travis.yml` will follow the merging of this PR.

Add configuration for GitHub Actions

---

.github/workflows/ci.yml
test/core/channel/algorithm_channel_relation.cpp

Add basic GitHub Actions configuration based on mp11
Remove Actions jobs using GCC 4.7 and 4.8 - unsupported compilers
Run b2 with --abbreviate-paths on Windows
The -std=c++1z is broken for clang-4.0 but no need to test it
Add -mbig-obj to GCC on Windows
- That is to avoid string table overflow and file too big
Define _GLIBCXX_USE_CXX11_ABI=0 for clang 3.5, 3.6, 3.7
- Should help avoid linker error:
`undefined reference to std::ios_base::failure::failure(char const*, std::error_code const&)`
Disable certain check in algorithm_channel_relation test for clang<3.8
(cherry picked from develop commit 81b4dc08bd9177bf9361194a66b0e70cfd6438e8)
- Cherry-picked from #544

ci: Add configuration for GitHub Actions to master branch

---

test/Jamfile

Most uses of cxxflags are wrong.
Use b2 warnings instead, e.g. warnings=pedantic

build: Remove most of uses of cxxflags from test/Jamfile

---

include/boost/gil/detail/mp11.hpp
test/core/pixel/test_fixture.hpp

Removed "#include <boost/mp11/mpl.hpp>"
at include/boost/gil/detail/mp11/hpp
and test/core/pixel/test_fixture.hpp

Removed two instaces of boost.mpl (Issue #483)

---

include/boost/gil/algorithm.hpp
test/core/image/image.cpp

Due to the different layout of planar images (e.g. `rgb8_planar_image_t`), construction of them using interleaved images(e.g. `rgb8_image_t`) failed on `std::unintialized_copy()` and this workflow needed special care.
This implementation of the constructor does-
1. allocate buffer according to the interleaved's dimensions.
2. default-constructs the elements.
3. copies the interleaved image.
fixes #478 which was opened by @mloskot

Support constructing a planar image from interleaved image

---

example/hessian.cpp
example/mandelbrot.cpp
include/boost/gil/channel_algorithm.hpp
include/boost/gil/color_base.hpp
include/boost/gil/color_convert.hpp
include/boost/gil/image_processing/harris.hpp
include/boost/gil/image_processing/hessian.hpp
include/boost/gil/image_processing/numeric.hpp

This PR fixes multiple warnings showing up during boost build process. Including the fixes of the examples, and some other warnings from core header files.
#436
https://github.com/boostorg/gil/blob/81b4dc08bd9177bf9361194a66b0e70cfd6438e8/include/boost/gil/channel.hpp#L651
Fixing this warning causes a test to fail and I couldn't figure out why that was happening, so I skipped fixing that one for now.

Fixed most of the warnings in the examples and many of the boost build process

---

include/boost/gil/extension/toolbox/image_types/subchroma_image.hpp

Fix warning: returning reference to local temporary object

---

test/Jamfile

The warnings, debug-symbols and other build properties
can (and should) be controlled via b2 command line options.
By the way, most of `<cxxflags>` uses in `Jamfile`-s [are usually incorrect](https://cpplang.slack.com/archives/C27KZLB0X/p1611538905042200).
Instead, [better option is to](https://cpplang.slack.com/archives/C27KZLB0X/p1611592269057100?thread_ts=1611553747.045400&cid=C27KZLB0X):
> use `warnings=pedantic` to control the warnings instead of `cxxflags` options directly
> either in `requirements` or in `default-build`, depending on whether you want to override it from the command line or not

Remove <cxxflags> and other cruft from Jamfile

---

include/boost/gil.hpp

Fixes #553 : Added missing headers and sorted them.

Review and update includes in boost/gil.hpp

---

.ci/coverage.sh
.github/workflows/coverage.yml

Adds Codecov GitHub Actions 
#548 & #532

Add Codecov to GitHub Actions

---

include/boost/gil/image_processing/diffusion.hpp

added missing header guards in
<boost/gil/image_processing/diffusion.hpp>

added missing header guards

---

CONTRIBUTING.md

Also, relabel Boost.Build to the current B2 name.

Repoint B2 refs to new non-boostorg home.

---

.azure-pipelines.yml
.github/workflows/ci.yml

Required by #526
See also https://github.com/boostorg/website/pull/562

ci: Remove GCC 5 on GitHub Actions and Azure Pipelines

---

include/boost/gil/extension/numeric/affine.hpp
test/extension/numeric/matrix3x2.cpp

The rotation function already existed however, the rotation was about the top-left vertex of the image as the origin, resulting in some parts being out of view. I have added a function that rotates the image about its center, using affine transformations, and scales it according to the dimensions of the source image.
This pull request is in reference to issue #533 
#533

Rotation of image by any arbitrary Angle

---

include/boost/gil/extension/dynamic_image/any_image.hpp
include/boost/gil/extension/dynamic_image/any_image_view.hpp
test/extension/dynamic_image/CMakeLists.txt
test/extension/dynamic_image/Jamfile
test/extension/dynamic_image/any_image_view.cpp

Fix `any_image_view<>::const_t` that currently returns an invalid type, see the provided test case that fails on `develop`.

Fix any_image_view::const_t

---

.github/workflows/ci.yml

The `compiler` property should trigger creation of `user-config.jam`
with the expected GCC 8 defined.
Something has changed (see image README-s below) on the GitHub Actions images or Boost.Build
and GCC 8 build job started failing:
/home/runner/work/gil/boost-root/tools/build/src/tools/gcc.jam:203: in gcc.init from module gcc
error: toolset gcc initialization:
error: version '8' requested but 'g++-8' not found and version '7.5.0' of default 'g++' does not match
e.g. https://github.com/boostorg/gil/pull/562/checks?check_run_id=2246393722
- Attempt to fix https://github.com/boostorg/gil/pull/562#issuecomment-812025806 (/cc @meshtag)
- Default toolsets seem to have been updated
- https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md 
- …

ci: Fix availability of toolsets in updated Ubuntu images of GitHub Actions

---

.github/workflows/ci.yml

Despite https://clang.llvm.org/cxx_status.html saying:
>  Clang 3.4 and later implement all of the ISO C++ 2014 standard.
The clang 3.5 suffers from the bug in C++14 mode causing failure of
Boost.Filesystem build with:
```
error: debug information for auto is not yet supported
error: debug information for auto is not yet supported
```
- Attempt to fix #562 (comment) (/cc @meshtag)
- https://github.com/boostorg/gil/pull/589
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800483

ci: Remove cxxstd=14 from clang 3.5 job on GitHub Actions

---

test/extension/io/bmp/bmp_old_test.cpp
test/extension/io/bmp/bmp_test.cpp
test/extension/io/jpeg/jpeg_old_test.cpp
test/extension/io/jpeg/jpeg_test.cpp
test/extension/io/png/png_old_test.cpp
test/extension/io/png/png_test.cpp
test/extension/io/pnm/pnm_old_test.cpp
test/extension/io/pnm/pnm_test.cpp
test/extension/io/raw/raw_test.cpp
test/extension/io/targa/targa_old_test.cpp
test/extension/io/targa/targa_test.cpp
test/extension/io/tiff/tiff_old_test.cpp
test/extension/io/tiff/tiff_test.cpp

Tests update missing from commits switching the `any_image` to modern variant2 and mp11.
- https://github.com/boostorg/gil/issues/453#issuecomment-833898207

test: Catch up IO with switch to variant2 migration

---

doc/design/pixel.rst

Update pixel design documentation after #274.
- #274.

Update pixel design documentation for MP11 changes

---

include/boost/gil/extension/io/bmp/tags.hpp
include/boost/gil/extension/io/jpeg/tags.hpp
include/boost/gil/extension/io/png/tags.hpp
include/boost/gil/extension/io/pnm/tags.hpp
include/boost/gil/extension/io/raw/tags.hpp
include/boost/gil/extension/io/targa/tags.hpp
include/boost/gil/extension/io/tiff/tags.hpp

Replace the *simple-template-id*s used in the IO extension tags as constructor names for specializations of `image_read_info` and `image_read_settings` with the associated plain class names.
resolves #616

Fix C++20 incompatibilities in IO extensions

---

CONTRIBUTING.md

The Table of contents link to B2 seemed to be broken as clicking on it did not take you anywhere. This PR fixes that.
N/A
This is a very minor fix.

CONTRIBUTING.md: fix TOC link to B2

---

include/boost/gil/image_processing/diffusion.hpp

@simmplecoder  Could you confirm these were just unused and not meant to be used but overlooked?
```
../../boost/gil/image_processing/diffusion.hpp:160:14: warning: unused variable ‘first’ [-Wunused-variable]
160 |         auto first = stencil.begin();
|              ^~~~~
../../boost/gil/image_processing/diffusion.hpp:161:14: warning: unused variable ‘last’ [-Wunused-variable]
161 |         auto last = stencil.end();
|              ^~~~
```

Fix warning: unused variable in diffusion.hpp

---

include/boost/gil/extension/numeric/convolve.hpp
test/extension/numeric/convolve_2d.cpp

Convolve_2d currently does not work  with images using float32_t channel model due to a trivial issue. This PR fixes that.
Fixes #575

Fix convolve_2d for images with float32_t channel model

---

test/core/image_processing/CMakeLists.txt

I don't think we need multiple loops here unless I am missing something? @simmplecoder

Refactor CMake test config

---

doc/io.rst
include/boost/gil/io/detail/filesystem.hpp
include/boost/gil/io/make_backend.hpp
include/boost/gil/io/make_dynamic_image_reader.hpp
include/boost/gil/io/make_dynamic_image_writer.hpp
include/boost/gil/io/make_reader.hpp
include/boost/gil/io/make_scanline_reader.hpp
include/boost/gil/io/make_writer.hpp
include/boost/gil/io/path_spec.hpp
test/extension/io/bmp/bmp_make.cpp
test/extension/io/bmp/bmp_test.cpp
test/extension/io/jpeg/jpeg_test.cpp
test/extension/io/paths.hpp
test/extension/io/png/png_file_format_test.cpp
test/extension/io/png/png_read_test.cpp
test/extension/io/png/png_write_test.cpp
test/extension/io/raw/raw_test.cpp
test/extension/io/simple_all_formats.cpp
test/extension/io/targa/targa_test.cpp
test/extension/io/tiff/tiff_test.cpp

If neither <filesystem> nor <experimental/filesystem> is detected,
then require <boost/filesystem.hpp>.
If user defines BOOST_GIL_IO_USE_BOOST_FILESYSTEM macro,
then <boost/filesystem.hpp> is pre-selected and required,
and search for any of the C++ standard implementation is skipped.
Remove end-user macro BOOST_GIL_IO_ADD_FS_PATH_SUPPORT
Require tests to always build with support of either
detected C++ filesystem or pre-selected Boost.Filesystem.
- #222 - this PR removes `BOOST_GIL_IO_ADD_FS_PATH_SUPPORT` macro

Add support for <filesystem> to IO

---

include/boost/gil/algorithm.hpp
test/core/algorithm/for_each_pixel.cpp

Fix for_each_pixel for non 1d iterable views

---

.azure-pipelines.yml
.github/workflows/ci.yml

Ubuntu 16.04 is no longer available for GitHub Actions, because support for it has ended. However, some build jobs still try to use Ubuntu 16.04. This pull request tries to change that for those cases where a replacement with Ubuntu 18.04 is possible.
Note: Some older Clang versions (Clang 3.8 and older) seem to be unavailable in the APT package repository, so those are not
changed to 18.04. _This is intended._ Maybe tests for Clang 3.4 to Clang 3.8 should be removed, but that is probably worth another discussion.
Ubuntu 16.04 has been removed from GitHub in 2021. See <https://github.com/actions/virtual-environments/issues/3287> for more information.

Replace Ubuntu 16.04 with Ubuntu 18.04 in some GitHub Actions jobs

---

.github/workflows/ci.yml

The name of the clang-9 package was missing, so it was not installed. This PR fixes it, so that Clang 9 gets installed an can be used during CI.
None.

Fix Clang 9 build on GitHub Actions

---

.azure-pipelines.yml

The image `macOS-10.14` is not available anymore, but `macOS-10.15` is still available. So this PR simply switches to that image.
If this is successful, then at least all the Azure pipeline builds of GIL are passing. :)
See <https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml> for available images in Azure pipelines.
This builds on the following idea mentioned in #642:
> As a general idea, we should probably make sure that the existing CI pipelines pass (except for the outdated stuff that may potentially get removed). Otherwise we may just be migrating existing build failures to another CI configuration with boost-ci.

Switch Azure's macOS build to supported OS version

---

.github/workflows/ci.yml

The Windows-2016 environment for GitHub Actions has been retired in March 2022, so it's not available anymore. For further information on that see <https://github.com/actions/virtual-environments/issues/4312>. However, we can test on the newer Windows 2022 environment instead. This also brings Visual Studio 2022.
So this pull request removes the GitHub Actions job using the Windows 2016 environment and introduces a new one with the Windows 2022 environment.
See https://github.com/actions/virtual-environments/issues/4312 for the removal announcement of the `windows-2016` environment.

ci: Switch GitHub Action's MSVC build to supported OS version

---

.azure-pipelines.yml

The images with Windows Server 2016 / Visual Studio 2017 have
been deprecated by Microsoft and are in the process of being
removed completely, so that no further builds with that image
will be possible.
I've just encountered the problem in https://github.com/boostorg/gil/pull/651
where the VS 2017 / Windows 2016 builds refused to start:
https://dev.azure.com/boostorg/gil/_build/results?buildId=1813&view=results
For reference, see
* <https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/>
* <https://github.com/actions/virtual-environments/issues/5238>
* <https://github.com/actions/virtual-environments/issues/5403>
Since it seems that Microsoft is basically using the same build
environments on both Azure and GitHub Actions when it comes to
Windows and Visual Studio, I …

ci: remove Windows Server 2016 from builds on Azure Pipelines

---

include/boost/gil/extension/io/png/detail/write.hpp

While `is_equal_to_sixteen` should (as the name suggests) check for equality to 16, it actually checked whether the bit depth was less than 16.
Since Boost.MP11 does not contain an `mp11::mp_equal` but only `mp11::mp_less`, the equality check is performed by making sure that
* the bit depth is not less than 16,
* 16 is not less than the bit depth,
* and both of those hold true.
It's a bit laborious, but it works.
The wrong comparison was introduced by PR #274 in https://github.com/boostorg/gil/commit/5611bd58071873d6346fe3cc05fe86c72f697717#diff-e2c958c778b464b94146992b6aeb7c814839ddbcbbb901f9f4175e797fa543d2 when `boost::mpl` was replaced with `boost::mp11`. In that commit the original `mpl::equal_to` was replaced by `mp11::mp_less`. To be fair though, unlike MPL the MP11 library does …

fix: is_equal_to_sixteen in PNG I/O was less-than test

---

include/boost/gil/extension/io/bmp/detail/read.hpp
include/boost/gil/extension/io/bmp/detail/write.hpp
include/boost/gil/extension/io/jpeg/detail/read.hpp
include/boost/gil/extension/io/jpeg/detail/write.hpp
include/boost/gil/extension/io/png/detail/read.hpp
include/boost/gil/extension/io/png/detail/write.hpp
include/boost/gil/extension/io/pnm/detail/read.hpp
include/boost/gil/extension/io/pnm/detail/write.hpp
include/boost/gil/extension/io/raw/detail/read.hpp
include/boost/gil/extension/io/targa/detail/read.hpp
include/boost/gil/extension/io/targa/detail/write.hpp
include/boost/gil/extension/io/tiff/detail/read.hpp
include/boost/gil/extension/io/tiff/detail/write.hpp
include/boost/gil/io/detail/dynamic.hpp

Renamed `io/dynamic_io_new.hpp` to `io/detail/dynamic.hpp`. 
The function `construct_matched` was only used by other detail headers, thus I moved the function into the detail namespace as already suggested in the issue. Additionally I moved the whole file into the detail directory, because it only contains details now.
Fixes #189

refactor: Renamed io/dynamic_io_new.hpp to io/detail/dynamic.hpp

---

include/boost/gil/pixel_numeric_operations.hpp
test/core/pixel/pixel_numeric_operations.cpp
test/core/pixel/pixel_numeric_operations_float.cpp

Closes #368 
Renamed `gil::pixel_multiply_t` to `gil::pixel_multiplies_t` and `gil::pixel_divide_t` to `gil::pixel_divides_t`.

unified naming for pixel and channel operations

---

include/boost/gil/extension/dynamic_image/algorithm.hpp
test/extension/dynamic_image/Jamfile
test/extension/dynamic_image/algorithm/Jamfile
test/extension/dynamic_image/algorithm/for_each_pixel.cpp

feat: Added for_each_pixel overload for any_image

---

doc/design/channel.rst
doc/design/color_space.rst
doc/design/image.rst
doc/design/image_view.rst
doc/design/pixel.rst
doc/design/pixel_iterator.rst
doc/design/pixel_locator.rst
doc/design/point.rst

This PR fixes broken links in the "See also" section of various documentation pages.
Fixes #591.
Compare:
* Current state: https://boostorg.github.io/gil/html/design/point.html
* links in "See also" are broken (404)
vs.
* fixed state: https://striezel-stash.github.io/gil/html/design/point.html
* links in "See also" lead to reference pages

fix documentation links in "See also" sections

---

RELEASES.md

@mloskot:
This updates the release notes on master to be up to date with those from develop. Those are the release notes of GIL for Boost 1.75. As you know, Boost 1.75 has already been release and the contained text was part of the release notes for that release: https://www.boost.org/users/history/version_1_75_0.html
The sole intention of this PR is to get the release notes file on master up to date with what already has been released.
(Cherry-pick of 8b1c2d3ea4eb5bf0a1e7e093862962313dd6c2bb from develop.)
**Note:** This PR targets the branch `master`, _not_ `develop` as PRs usually do. That is intentional.
Consider this the first "baby step" for a possible next release of GIL. See #663 for the ongoing discussion.

release notes update up to Boost 1.75

---

include/boost/gil/image_processing/diffusion.hpp

The variable `dims` is not used and can cause a compiler warning.
It causes compiler warning, e.g. here:
https://web.archive.org/web/20220511164304/https://www.boost.org/development/tests/develop/output/teeks99-06-dc9-2a-64onaarch64-gil-clang-linux-9~c++2a-warnings.html#anisotropic_diffusion (archived from [the original](https://www.boost.org/development/tests/develop/output/teeks99-06-dc9-2a-64onaarch64-gil-clang-linux-9~c++2a-warnings.html#anisotropic_diffusion), because that changes with every build on the `develop` branch)
```
../boost/gil/image_processing/diffusion.hpp:373:19: warning: unused variable 'dims' [-Wunused-variable]
1 warning generated.
```

chore: Remove unused variable in diffusion.hpp

---

include/boost/gil/extension/io/bmp/detail/write.hpp
include/boost/gil/extension/io/jpeg/detail/write.hpp
include/boost/gil/extension/io/png/detail/write.hpp
include/boost/gil/extension/io/pnm/detail/write.hpp
include/boost/gil/extension/io/targa/detail/write.hpp
include/boost/gil/extension/io/tiff/detail/write.hpp

The error was due to missing dynamic.hpp header that contained dynamic_io_fnobj. Adding the header back in to write.hpp headers of io extensions fixed the problem.
[#653 (comment)](https://github.com/boostorg/gil/pull/653#issuecomment-1125804514).
<s>Add test case(s)</s> N/A (run build and tests locally, all passed)

Fixed io extension build error

---

RELEASES.md

Includes changes up to commit 25 (hash [434e78f76](https://github.com/boostorg/gil/commit/434e78f76b5179369738f25a553b74cbaf886218)) from the table shown in <https://github.com/boostorg/gil/issues/667>.
See #667.

docs: Add partial release notes for Boost 1.80

---

RELEASES.md

Includes changes up to commit 106 (hash 36a45e3af) from the table shown in <https://github.com/boostorg/gil/issues/667>. Those are all commits form the recent grand merge.
Continuation of #670.
While PR 670 was merged I was working on getting the relavant changes from the remaining commits into the release notes. That was actually faster than expected, due to not all minor changes being relevant (see https://github.com/boostorg/gil/pull/670#pullrequestreview-971415430).
See also #667 for the release preparations in general and for the list of commits that the release notes cover.

docs: Add remaining part of release notes for Boost 1.80

---

include/boost/gil/device_n.hpp

devicen_t<2> was possible in Boost 1.71, but broke in Boost 1.72.
Now it's possible to use it again.
Since there was no real need to disallow it in the first place, I adjusted the `static_assert` which prevented it to allow two components, too.
Fixes #519.
See that issue for more information.

fix: re-allow devicen_t with two color components

---

example/convolution.cpp
include/boost/gil/extension/numeric/kernel.hpp
test/core/channel/channel_numeric_operations.cpp

Replaces the use of the deprecated header `<boost/gil/extension/numeric/channel_numeric_operations.hpp>` by the newer header `<boost/gil/channel_numeric_operations.hpp>`. (Move occurred as part of #573.)
This PR also fixes other two instances related to the move + deprecation of headers from the numeric extension.
Using the deprecated header causes a warning like
```
../boost/gil/extension/numeric/channel_numeric_operations.hpp:14:1: warning: This header is deprecated. Use <boost/gil/channel_numeric_operations.hpp> instead. [-W#pragma-messages]
1 warning generated.
```
Warning occurs when running tests, e. g. here: https://web.archive.org/web/20220518134058/https://www.boost.org/development/tests/develop/output/teeks99-dkr-dc12-20-gil-clang-linux-12~c++20-warnings.html#channel_numeric_oper …

chore: do not use deprecated header in test or elsewhere

---

RELEASES.md

Announces the switch to C++14 with the next release, i. e. Boost 1.80.
See https://github.com/boostorg/gil/discussions/676 for the discussion to move to a newer standard.

docs!: announce switch from C++11 to C++14 with Boost 1.80

---

RELEASES.md
include/boost/gil/extension/dynamic_image/image_view_factory.hpp

`color_converted_view` has the same implementation and can be used as a replacement, providing the same functionality.
This builds on https://github.com/boostorg/gil/pull/660 by @marco-langer.
Since there needs to be a deprecation notice first before removing a feature, here it is.
Due to the fact that the switch to C++14 has been announced in #677, we can now officially use the [`[[deprecated]]` attribute](https://en.cppreference.com/w/cpp/language/attributes/deprecated) which was standardized in C++14.

chore!: deprecate any_color_converted_view

---

include/boost/gil/packed_pixel.hpp

Following the Rule of Zero, this PR removes the user-defined copy constructor and copy assignment operator from `packed_pixel`. The type is now trivially copyable and trivially assignable:
```C++
#include <boost/gil.hpp>
#include <boost/mp11.hpp>
#include <type_traits>
namespace gil = boost::gil;
namespace mp11 = boost::mp11;
int main()
{
using packed_channel_references_3 = typename gil::detail::packed_channel_references_vector_type
<
std::uint8_t,
mp11::mp_list_c<int, 3>
>::type;
using packed_pixel_gray3 = gil::packed_pixel
<
std::uint8_t,
packed_channel_references_3,
gil::gray_layout_t
>;
static_assert(std::is_trivially_copyable<packed_pixel_gray3>::value);
static_assert(std::is_trivially_assignable<packed_pixel_gray3, packed_pixel_gray3>::value);
return 0;
}
```

refactor: Make packed_pixel trivially copyable and assignable

---

meta/libraries.json

The switch to C++ 14 was already announced in #677, but the metadata was not updated at the same time.
Announcement to switch from C++11 to C++14 was merged in #677.

chore: update metadata for switch to C++ 14

---

include/boost/gil/extension/dynamic_image/image_view_factory.hpp

Fixes a deprecation warning bug for gcc 10.2, see also [this comment.](https://github.com/boostorg/gil/pull/660#issuecomment-1147735559)

Fix deprecation warning bug for gcc 10.2

---

include/boost/gil/extension/image_processing/diffusion.hpp
include/boost/gil/extension/image_processing/hough_parameter.hpp
include/boost/gil/extension/image_processing/hough_transform.hpp
include/boost/gil/extension/rasterization/circle.hpp
include/boost/gil/extension/rasterization/ellipse.hpp
include/boost/gil/extension/rasterization/line.hpp

This PR adds the missing include guard to the line rasterizer and fixes the include guards for circle and ellipse rasterizers.

fix: Added missing include guard to line rasterizer

---

test/extension/toolbox/color_convert_hsl.cpp
test/extension/toolbox/color_convert_rgb.cpp

Contributor of PR #505 posted GTest-based tests in.
This commit ports those tests to Boost.LightweightTest.
Closes #690

test: Add tests for RGB to HSL

---

include/boost/gil/io/detail/filesystem.hpp

PR #636 has added detection for the `<filesystem>` header, but now examples using the IO extensions can't be compiled with C++11 or C++14 anymore. This PR fixes this issue.
Compiling one of the examples, e.g.
```
g++ x_gradient.cpp -std=c++11 -ljpeg
```
results in
```
In file included from ../../boost/libs/gil/include/boost/gil/io/path_spec.hpp:11,
from ../../boost/libs/gil/include/boost/gil/io/get_read_device.hpp:13,
from ../../boost/libs/gil/include/boost/gil/io/get_reader.hpp:11,
from ../../boost/libs/gil/include/boost/gil/extension/io/jpeg/read.hpp:18,
from ../../boost/libs/gil/include/boost/gil/extension/io/jpeg.hpp:11,
from ../../boost/libs/gil/example/x_gradient.cpp:9:
../../boost/libs/gil/include/boost/gil/io/detail/filesystem.hpp:55:29: error: ‘filesystem’ is not a namespace-name …
```

fix: Detection of std::filesystem header

---

include/boost/gil/extension/io/tiff/detail/device.hpp
include/boost/gil/extension/io/tiff/detail/write.hpp

This PR replaces libtiff's fixed-size typedef `uint32` with C99's fixed-size typedef `std::uint32_t`.
Rational: libtiff's typedefs are deprecated since v4.3.0 and we already see this deprecation warning in our CI for builds with clang on macos-10.15.
C99's fixed-size typedefs and libtiffs typedefs are almost interchangeable, with the notable exception for 64 bit macOS and a breaking change between long and long long according to [this](https://gitlab.com/libtiff/libtiff/-/merge_requests/185) and [this](https://gitlab.com/libtiff/libtiff/-/merge_requests/205) discussion. Currently I don't think this will affect Gil as we only used `uint32` from libtiffs typedefs, but nevertheless it might be a good idea to check the impact of this PR on macOS builds before merging it into develop.

refactor: Replace deprecated libtiff v4.3 typedefs with C99 fixed-size integers

---

example/rasterizer_circle.cpp
example/rasterizer_ellipse.cpp
example/rasterizer_line.cpp
include/boost/gil/extension/rasterization/ellipse.hpp
test/extension/rasterization/ellipse.cpp

This PR implements some of the mentioned issues in [my other comment](https://github.com/boostorg/gil/pull/585#issuecomment-1144412220) regarding the ellipse rasterizer, namely:
- renamed `midpoint_elliptical_rasterizer` to `midpoint_ellipse_rasterizer`
- replaced colour vector with pixel type
- replaced std::array with point type for center and semi-axis
- removed unnecessary deep copies of temporaries.
- removed printing warnings to cout
There are still some open questions, e.g. why circle/line and ellipse rasterizer have different signedness for point types and why they implement the call operator differently. However, I am not sure if we are able to find any consensus on these topics before the deadline for Boost 1.80.

refactor: ellipse rasterizer

---

example/hough_transform_circle.cpp
example/rasterizer_circle.cpp
example/rasterizer_ellipse.cpp
example/rasterizer_line.cpp
include/boost/gil/extension/image_processing/hough_transform.hpp
include/boost/gil/extension/rasterization/apply_rasterizer.hpp
include/boost/gil/extension/rasterization/circle.hpp
include/boost/gil/extension/rasterization/ellipse.hpp
include/boost/gil/extension/rasterization/line.hpp
test/extension/image_processing/hough_circle_transform.cpp
test/extension/image_processing/hough_line_transform.cpp
test/extension/rasterization/circle.cpp
test/extension/rasterization/ellipse.cpp
test/extension/rasterization/line.cpp

This PR implements the `gil::apply_rasterizer()` free function mentioned in #680.
However, I had to change the API of all three rasterizers quite considerably in order to squeeze them through this common interface. I am not sure if all those API changes are still debatable if we consider the deadline for Boost 1.80 in three days on 29th of June.
If you look at the updated examples, the usability is improved considerable (in my opinion) and it is still worth it (in my opinion) to discuss the PR, but I also understand that it might be too late for these kind of major API changes.
#680

feat: added apply_rasterizer() free function

---

RELEASES.md

For Boost 1.80 we have announced switch from C++11 to C++14
as an intermediate step.
As we will be moving forward with refactoring and modernisations,
we are planning to switch to C++17 in (near) future Boost release.
- https://github.com/boostorg/gil/pull/677
- https://github.com/boostorg/gil/discussions/676

docs!: Announce plan to require C++17 after Boost 1.80

---

.appveyor.yml
.ci/azure-pipelines/steps-cmake-build-and-test.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
test/Jamfile

We have switched to C++14 for Boost 1.80
-  Closes #696
- Related to #699

ci: Remove C++11 build jobs after C++14 switch

---

CMakeLists.txt
test/extension/toolbox/CMakeLists.txt

- Follow-up to #677
- Related to #696

build: Update CMAKE_CXX_STANDARD from 11 to 14

---

CONTRIBUTING.md
README.md
doc/index.rst
doc/installation.rst
example/adaptive_histogram_equalization.md
example/adaptive_threshold.md
example/affine.md
example/anisotropic_diffusion.md
example/convolution.md
example/convolve2d.md
example/dynamic_image.md
example/harris.md
example/hessian.md
example/histogram.md
example/histogram_equalization.md
example/histogram_matching.md
example/hough_transform_circle.md
example/hough_transform_line.md
example/interleaved_ptr.md
example/mandelbrot.md
example/morphology.md
example/packed_pixel.md
example/rasterizer_circle.md
example/rasterizer_ellipse.md
example/rasterizer_line.md
example/resize.md
example/sobel_scharr.md
example/threshold.md
example/tutorial_histogram.md
example/x_gradient.md

Related to:
- #677
- #698
- #699

docs: Bump C++11 to C++14 as current required

---

test/core/image/CMakeLists.txt
test/core/image/Jamfile
test/core/image/empty_dimensions.cpp

Test fix #649
- May overlap with #423

test: Add test cases for image with empty dimensions

---

include/boost/gil/algorithm.hpp

This PR fixes a unused variable warning.
Compile this with `-Wall -Wextra -Wpedantic`
```C++
#include <boost/gil/extension/io/jpeg.hpp>
#include <boost/gil/extension/dynamic_image/dynamic_image_all.hpp>
namespace gil = boost::gil;
int main()
{
using my_image = gil::any_image<gil::gray8_image_t>;
my_image img;
gil::read_image("test.jpeg", img, gil::jpeg_tag{});
return 0;
}
```
Edit: fixed a second unused variable. This did not show up as a warning, I just saw it as I was browsing the algorithm.hpp file.

fix: Unused variable warning

---

include/boost/gil/extension/rasterization/ellipse.hpp
test/core/point/test_fixture.hpp
test/extension/rasterization/Jamfile
test/extension/rasterization/apply_rasterizer.cpp
test/extension/rasterization/circle.cpp
test/extension/rasterization/ellipse.cpp
test/extension/rasterization/line.cpp

This PR fixes a bug in `midpoint_ellipse_rasterizer::draw_curve()`, [which I have introduced in my other PR](https://github.com/boostorg/gil/pull/695) while working on the `apply_rasterizer` function. I have also added missing test cases to cover these invocations.

fix: broken build for midpoint_ellipse_rasterizer::draw_curve

---

README.md

This PR updates the README.md language badge from C++11 to C++14.
Also still needed: change the topic in the about section from "cplusplus-11" to "cplusplus-14".

docs: Updated readme language badge to C++14

---

test/extension/toolbox/color_convert_hsl.cpp
test/extension/toolbox/color_convert_rgb.cpp

This PR fixes the broken build of the test project for gcc-5 and closes thereby #709 and #710.
Maybe this PR will also close #711. I had difficulties to reproduce the bug, as using godbolt [does not reproduce this bug using clang 3.9](https://godbolt.org/z/PxcTEEWq1).

fix: Broken build of test project for gcc-5

---

RELEASES.md

That typo was already fixed for the Boost website in commit <https://github.com/boostorg/website/commit/be797166146823e39a4edc895bf65aaf419cecc2>, but the change has not made it back to GIL - yet.
Function that was moved in #653 is named `construct_matched`, not `construct_method`.

docs: fix typo in release notes for #653

---

.github/workflows/ci.yml

GitHub started the deprecation process for Ubuntu 18.04 Action runners on 2022-08-08, and Ubuntu 18.04 will be completely unsupported by 2022-12-01 (if things proceed as planned).
So this PR tries to replace all Ubuntu 18.04 runners with the next newest Ubuntu 20.04 runner. I don't think this will work on first try, but we need to start somewhere.
So this commit replace those Ubuntu 18.04 jobs with the next newest Ubuntu 20.04 runner that have shown to still work with the newer version. The other five GHA jobs with Ubuntu 18.04 (gcc-6, gcc-7, clang++-3.9, clang++-4.0, clang++-5.0) still need to be dealt with separately later.
See <https://github.blog/changelog/2022-08-09-github-actions-the-ubuntu-18-04-actions-runner-image-is-being-deprecated-and-will-be-removed-by-12-1-22/> for the …

ci: replace Ubuntu 18.04 on GHA with Ubuntu 20.04

---

doc/_static/boost.css
doc/_templates/layout.html

Hi,
The current boostorg/boost bundle has been created using Sphinx version 1.5.6 
If upgrading _all_ packages and Sphinx changes to 5.2.1 , the gil docs are slightly broken. 
- Search doesn't work  
- bullet lists are widely spaced   
Researched the problems in https://github.com/sphinx-doc/sphinx/issues . After some experimentation, it looks like the fix in this pull request solves the issues.

Support newer version of Sphinx

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/docs.yaml

Updates the `actions/checkout` action used in the GitHub Actions workflow to its newest major version.
Changes in [actions/checkout](https://github.com/actions/checkout):
> ## v3.1.0
> - Use @actions/core `saveState` and `getState`
> - Add `github-server-url` input
>
> ## v3.0.2
> - Add input `set-safe-directory`
>
> ## v3.0.1
> - Fixed an issue where checkout failed to run in container jobs due to the new git setting `safe.directory`
> - Bumped various npm package versions
>
> ## v3.0.0
>
> - Update to node 16
As far as I can tell this should all be backwards compatible, so I do not expect any breakage.

ci: update actions/checkout in GitHub Actions workflows to v3

---

include/boost/gil/detail/math.hpp
include/boost/gil/image_processing/convolve.hpp
test/core/image_processing/convolve_2d.cpp

This PR fixes the issue explained in #722.

fix: Convolution in convolve_2d.

---

include/boost/gil/extension/dynamic_image/image_view_factory.hpp
test/extension/dynamic_image/image_view_factory.cpp

The function color_converted_view for dynamic views with a custom color converter ignores the provided color converter. 
This pr fixes this issue as well as some compilation failures related to it. A corresponding test is included

Fixed custom color converter in dynamic_factory and added corresponding

---

include/boost/gil/locator.hpp

`locator` implementation uses `make_step_iterator()` but `step_iterator.hpp` is not included.

Make locator.hpp self contained

---

include/boost/gil/locator.hpp

On Mar 21, 2023, at 8:59 AM, Samuel DEBIONNE via Boost [<boost@lists.boost.org>](mailto:boost@lists.boost.org) wrote:
>
> Hello,
> I would like to merge a "missing include" fix from Boost.GIL to master:
>
> https://github.com/boostorg/gil/pull/729
Go ahead
— Marshall

fix: Make locator.hpp self contained (#729)

---

.github/workflows/ci.yml

ci: ubuntu-18.04 environment is deprecated

---

.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/docs.yaml

This updates [`actions/checkout`](https://github.com/actions/checkout) to v4, it's current version.
Changelog:
> ## v4.1.0
> - Add support for partial checkout filters
>
> ## v4.0.0
> - Support fetching without the --progress option
> - Update to node20

ci: update actions/checkout in GitHub Actions workflows to v4

---

.github/workflows/coverage.yml

This pull request fixes the `E: Package 'python' has no installation candidate` error in the coverage workflow by providing an existing package.
The Python package in Ubuntu 22.04 is `python3`, but I decided to go for [`python-is-python3`](https://packages.ubuntu.com/jammy/python-is-python3) instead, because that makes sure that `python3` is installed (as dependency) and also creates a symlink from `/usr/bin/python` to `python3` as a way to make sure that commands with just `python` (instead of `python3`) also invoke the installed version of Python 3.
See https://github.com/boostorg/gil/actions/runs/7317309558/job/19932692704 for an example of a currently failing coverage job.

ci: fix Python package in coverage workflow

---

test/extension/io/png/png_file_format_test.cpp

Removed usage of Boost.Filesystem APIs that were deprecated and then removed.

Update Boost.Filesystem usage

---

include/boost/gil/extension/histogram/std.hpp
include/boost/gil/extension/io/tiff/detail/read.hpp
include/boost/gil/histogram.hpp
include/boost/gil/image_processing/histogram_equalization.hpp
include/boost/gil/image_processing/histogram_matching.hpp

The purpose of this PR is to work around min/max macro conflicts with windows.h when using Win32-API programming on MSVC (in Windows). Unfortunately windows.h defines min() and max() macros that conflict with the standard C++ ones.

Portable minmax Win32-API workaround #744

---

CMakeLists.txt

CMake was unopinionated about what filesystem is used and required excessive flag setting. Now it clarifies that boost::filesystem is default and std::filesystem is used in case
BOOST_GIL_USE_BOOST_FILESYSTEM is off and CMAKE_CXX_STANDARD>=17.
Apparently we did not explicitly linked to boost libraries anyway. Either that, or I overlooked it.
https://github.com/boostorg/gil/issues/742

Guard boost::filesystem usage

---

include/boost/gil/io/path_spec.hpp

Fixes #733.
Issue:
The length calculation of the destination buffers for conversions from `std::wstring` to `std::string` or `wchar_t*` to `char*` is incorrect, causing a buffer overflow in some cases.
Explanation:
The current code uses `wcslen()` to "calculate" the length of the converted destination string buffer. However, `wcslen()` is just a `strlen()` for `wchar_t*` strings. So it returns the number of wide characters in a `wchar_t*` string, but this does not need to be the same as the number of narrow characters (that is: `char`) in the converted string (`char*` or `std::string`). It just happens to be the same, if the wide character string only uses characters of the English alphabet where each wide character is converted to exactly one narrow character.
So the length has to be …

fix wrong buffer size in path string conversion functions

---

include/boost/gil/io/device.hpp

Adds `tell()` and `error()` functions to `istream_device` and `ostream_device` classes.
The class `file_stream_device` already has such functions, and now both `istream_device` and `ostream_device` have them, too, making the device classes more consistent.
Closes #724.
See #724.

feat: add tell() and error() functions to istream + ostream devices

---

RELEASES.md

Includes release notes for the changes seen in the table in #748, i.e. the changes for a potential Boost 1.86 release of GIL.
See #748.

docs: Add release notes for Boost 1.86

---

.github/workflows/ci.yml

This pull request attempts to fix two issues with the CI jobs:
* failure of container-based jobs seen in https://github.com/boostorg/gil/actions/runs/9796328751
* removal of macOS 11 from the available runner images (discussed earlier here: https://github.com/boostorg/gil/pull/749#issuecomment-2207435037)
Node.js 20 is not supported in older containers like `ubuntu:18.04`, but GitHub Actions nowawadays forces the use of Node.js 20, even if the action itself still specified Node.js 16 as the version to use. The result is that e.g. `actions/checkout@v3` fails in the containers, although it should not (because v3 is still specified Node.js 16).  See <https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/> for more information on …

CI improvements and workarounds

---

.github/workflows/coverage.yml

This PR updates [`codecov/codecov-action`](https://github.com/codecov/codecov-action) to v4, it's current version.
* It get's rid of the warning in CI due to outdated Node versions used by the older versions of the actions, e.g. as seen here: https://github.com/boostorg/gil/actions/runs/10054788474
> The following actions uses node12 which is deprecated and will be forced to run on node16: codecov/codecov-action@v1.2.1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
Version 4 of the action [uses Node 20](https://github.com/codecov/codecov-action/blob/e28ff129e5465c2c0dcc6f003fc735cb6ae0c673/action.yml#L120).
* As far as I understand, version 1.x of the action has been deprecated: …

ci: update codecov/codecov-action in GitHub Actions workflow to v4

---

include/boost/gil/extension/dynamic_image/image_view_factory.hpp

Fix dynamic transposed_view

---

.github/workflows/ci.yml

Fix node 20 issue on GHA CI

---

doc/_templates/layout.html

When building the docs with Sphinx 8.1.3 there is an error about 'logo'.  
Where is the variable originally defined?  
The modification in this PR seems to solve the problem.

docs: modify logo variable

---

include/boost/gil/io/typedefs.hpp

Closes https://github.com/boostorg/gil/issues/760

Fix is_floating_point symbol is not a class template

---

.github/workflows/ci.yml

Add CI jobs for newer versions of GCC, from GCC 11 to GCC 15.
_~Currently a draft only, because there may be some new errors popping up.~
Not a draft anymore, because none of the new builds failed._
None.

ci: add jobs for newer GCC versions

---

.github/workflows/ci.yml

Add CI jobs for newer versions of Clang/LLVM, from Clang 11 to Clang 20.
_~Currently a draft only, because there may be some new errors popping up.~
Not a draft anymore, because now none of the new Clang builds fail anymore._
None.

ci: add newer Clang versions
